/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord": "加入 Discord",
    "Credits:": "鸣谢:",
    "Hidden": "隐藏",
    "Heirloom": "传家宝",
    "Item": "物品",
    "Other": "其他",
    "Etc": "其它",
    "Log": "日志",
    "Monday": "周一",
    "Tuesday": "周二",
    "Skills": "技能",
    "Start Journey": "开始旅程",
    "Type": "类型",
    "Tooltip": "工具提示",
    "Use": "使用",
    "World Navigation": "世界导航",
    "Enchant": "附魔",
    "Equipment": "装备",
    "Equip": "装备",
    "Combat": "战斗",
    "Action Window": "行动窗口",
    "(Icons)": "(图标)",
    "(Battlers)": "(战士)",
    ". This happens and is explained in full after finishing floor 1 of the tower. It is recommended not to protract the first run before getting there and fully understanding this mechanic.": "．这是在完成塔的第一层后发生的。在完全理解这一机制之前，建议不要延长第一次运行时间。",
    "Yes, filling your belly would be a good start.": "是的，填饱肚子是个好的开始。",
    "Welcome to the Climb, if you see/hear this, you are using a screenreader. This game is unfortunately not made with people like you in mind, I am sorry. However, I did do some tweaks to at least enable you to play somewhat. The most important thing is knowing that \"mouse over\" is extremely important in this game. Crucial information is displayed when you \"mouse over\" things, like, but not limited to, inventory. If you find a \"clickable\", it most likely has a tooltip. There is a tooltip element that exists near the bottom of the page, it is marked by a heading level 2. This element is updated whenever you mouse over something that does have a tooltip. Once again I am sorry for not being able to spend more time making the game more accessible, but I do hope you have fun with the limited functionality available. If you think there are some minor tweaks that would make the experience more enjoyable to play, let me know on discord.": "欢迎来到攀登，如果你看到/听到这个，你正在使用屏幕阅读器。不幸的是，这个游戏并没有考虑到像你这样的人，我很抱歉。然而，我确实做了一些调整，至少让你能玩一些。最重要的是要知道“鼠标悬停”在这个游戏中是非常重要的。当你“鼠标移到”物品上时，关键信息就会显示出来，比如，但不限于，库存。如果你发现一个“可点击的”，它很可能有一个工具提示。在页面底部附近有一个工具提示元素，它被标记为标题级别2。当您将鼠标移到有工具提示的东西上时，此元素就会更新。我再次为不能花更多时间让游戏更容易上手而感到抱歉，但我希望你能在有限的功能中玩得开心。如果你认为有一些小的调整可以让游戏体验更愉快，请在Discord上告诉我。",
    "The game was not designed for small devices such as mobile phones. Text may be hard to read and hover tooltips hard to access. This includes important gameplay explanations, lore and questlines. It is strongly recommended to play the game on a desktop or a laptop instead..": "这款游戏不是为手机等小型设备设计的。文本可能难以阅读，悬停工具提示难以访问。这包括重要的游戏玩法解释，传说和任务线。强烈建议在台式机或笔记本电脑上玩此游戏。",
    "A long journey lies ahead.": "前面还有很长的路要走。",
    "Aekashics": "美学",
    "And living among these brave heroes is you, a nobody. A nobody with a dream - to conquer the tower. Or at least earn enough to fill your belly.": "而你，一个无名小卒，生活在这些勇敢的英雄之中。一个没有梦想的无名小卒——征服高塔。或者至少赚到足够填饱肚子的钱。",
    "And then you should probably check around the Training Grounds in the City.": "然后你应该去城里的训练场看看。",
    "Brought to you by Motas.": "由Motas为您带来。",
    "Clockwork Raven": "发条乌鸦",
    "Everyone who provided feedback and suggestions": "所有提供反馈和建议的人",
    "finalbossblues": "finalbossblues",
    "Full of monster, but also treasures, it attracted countless adventurers, and a bustling city was built around it.": "充满了怪物，也有宝藏，它吸引了无数的冒险家，并在它周围建立了一个繁华的城市。",
    "Information Window": "信息窗口",
    "Inventory": "库存",
    "It has been 500 years since the Tower appeared.": "自从塔出现以来，已经有500年了。",
    "Join us on discord": "加入我们的Discord吧",
    "Journal": "日记",
    "MDEF": "魔法防御",
    "Neutral": "中立",
    "Pipoya": "Pipoya",
    "Status": "状态",
    "Thank you for playing": "谢谢你的参与",
    "The Beginning": "开始",
    "The tower pierces through the heavens, its top nowhere to be seen.": "这座塔高耸入云，看不到塔顶。",
    "There are new quests available in the Adventurers' Guild.": "在冒险家公会中有新的任务。",
    "This game features a prestige mechanic, meaning it resets parts of your progress": "这款游戏的特色是声望机制，这意味着它会重置你的部分进度",
    "This is a demo with limited content.": "这是一个内容有限的演示。",
    "Unremarkable": "平平无奇",
    "Vitals": "生命值",
    " Stats": "属性",
    ": Press shift to show controls overlay, this allows you to set item as favorite, hide it into the hidden tab, delete it and later in the game - feed it. Use right click on inventory filters to use them as toggles instead of tabs.": "：按shift显示控件覆盖，这可以让你设置物品为收藏，隐藏到隐藏标签，删除它，后来在游戏中提供它。在库存过滤器上使用右键将它们用作开关而不是选项卡。",
    ": Some actions will remove equipment from your inventory (completing quests, feeding). These actions only count and remove clean equipment. An equipment is clean when it has no experience, no rank, no socketed enchant (or card) and is not an heirloom (except runes), equipped, favorite or hidden. It's basically a new piece of equipment you have not interacted with.": "：一些动作会从你的库存中移除装备（完成任务，喂养）。这些动作只计算和移除干净的装备。当一个装备没有经验，没有等级，没有嵌套的附魔（或卡牌），不是传家宝（除了符文），装备，最爱或隐藏时，它就是干净的。它基本上是一个你没有与之互动的新装备。",
    "Pause": "暂停",
    "Pauses the game.": "暂停游戏。",
    "Intelligence": "智力",
    "Dark Mode": "深色模式",
    "Removes": "移除",
    "Quests": "任务",
    "Poison": "药水",
    "Save Export": "导出存档",
    "Strength": "力量",
    "Updates": "更新",
    "Weapon Element": "武器元素",
    "Travelers": "旅行者",
    "Your progress is saved.": "您的游戏进度已保存。",
    "Burning": "燃烧",
    "Bleeding": "流血",
    "Bestiary": "图鉴",
    "Bandage": "绷带",
    "Armor Element": "护甲元素",
    "About": "关于",
    "Clean items": "清理物品",
    ": Pressing 0-9 while hovering over an item allows you to set a hotkey. Using the hotkey uses the item. You can also hold the hotkey for rapid usage.": "：当鼠标悬停在一个项目上时按0-9键可以设置一个热键。使用热键可以使用该项。也可以按住热键快速使用。",
    "A jug of enchanted water, effective at dousing basic magical fire.": "一壶施了魔法的水，能有效地扑灭基本的魔法火焰。",
    "A piece of dry bread. Somewhat filling, no risk of food poisoning, cheap. Nothing to complain about, right? Right?": "一块干面包。有点饱腹感，没有食物中毒的风险，便宜。没什么好抱怨的，对吧？对吧?",
    "Alternatively, you can press and hold the shift key.": "或者，您也可以按住shift键。",
    "Antidote": "解药",
    "Check out what's new": "看看有什么新消息",
    "Click this icon to remove the golden highlight.": "单击此图标以移除金色高光。",
    "Click this to export your save into a text file.": "单击此按钮将您的保存导出为文本文件。",
    "Click to toggle.": "单击进行切换。",
    "Cloth bandage, effective at stopping bleeding.": "布绷带，止血效果好。",
    "Consumable / Food": "消耗品/食品",
    "Consumable / Medicine": "消耗品/药品",
    "Controls": "控制",
    "Damage Reduction": "伤害减免",
    "Dexterity": "灵巧",
    "Dims the background.": "调暗背景。",
    "Dry Bread": "干面包",
    "Enchanted Water": "附魔之水",
    "Equipment": "装备",
    "HP Regeneration": "生命回复",
    "Increase magical damage dealt.": "增加魔法伤害。",
    "Increase physical damage dealt.": "增加物理伤害。",
    "Increases critical chance.": "增加暴击几率。",
    "Inventory Guide": "库存指南",
    "Learned Diagrams": "学习图表",
    "Magical Defense": "魔法防御",
    "Mixture of medicinal ingredients, effective at stopping most poisons.": "混合的药物成分，有效地阻止大多数毒药。",
    "Normal Speed": "正常速度",
    "Opens the about overlay.": "打开关于弹出层。",
    "Opens the inventory controls. Click again to close.": "打开库存控制。再次单击关闭。",
    "Opens the settings overlay.": "打开设置弹出层。",
    "Opens the updates overlay.": "打开更新弹出层。",
    "Reduces all damage received (flat amount).": "减少所有伤害（固定数量）。",
    "Reduces magical damage received (percentage).": "减少魔法伤害（百分比）。",
    "Runs the game at normal speed.": "以正常速度运行游戏。",
    "The element of your armor. Affects damage received based on enemy weapon element.": "你盔甲的元素。根据敌人的武器元素影响受到的伤害。",
    "The element of your weapon. Affects damage dealt based on enemy armor element.": "你武器的元素。影响对敌方护甲造成的伤害。",
    "Reset Game": "重置游戏",
    "Drinks Consumed:": "消耗的饮料:",
    "Death Count:": "死亡次数:",
    "Cards Obtained:": "获得的卡片:",
    "Water Killed:": "水击杀:",
    "Races Killed:": "种族击杀:",
    "Neutral Killed:": "自然击杀:",
    "Formless Killed:": "无形击杀:",
    "Enemies Killed:": "击杀的敌人:",
    "Construct Killed:": "结构体击杀:",
    "Bosses Killed:": "击杀的Boss:",
    "Burning Damage Dealt:": "造成的燃烧伤害:",
    "Bleeding Damage Dealt:": "造成的流血伤害:",
    "Bleeding Damage Received:": "受到的流血伤害:",
    "Burning Resistance": "火焰抵抗",
    "Combat Mastery Exp": "战斗精通经验值",
    "Alchemy Exp": "炼金术经验值",
    "Blacksmithing Exp": "锻造经验值",
    "Trading Exp": "交易经验值",
    "Enchanting Exp": "附魔经验值",
    "Chronomancy Exp": "时卜术经验值",
    "Tailoring Exp": "裁缝经验值",
    "Cooking Exp": "烹饪经验值",
    "Water Affinity Exp": "水亲和力经验值",
    "Date and Time": "日期和时间",
    "Defense": "防御",
    "discord link": "Discord链接",
    "Discount": "折扣",
    "Discount now applies on workstation purchases": "折扣现在适用于购买工作站",
    "Damage Received": "受到的伤害",
    "Damage Dealt": "造成的伤害",
    "Crit Power": "暴击伤害",
    "Cooking": "烹饪",
    "Drop Rate": "掉落率",
    "Enchanting": "附魔",
    "Elements Killed": "击杀的元素",
    "Generate save": "生成存档",
    "Generate Save": "生成存档",
    "General": "常规",
    "Spells Cast:": "施放的法术:",
    "Tailoring": "裁缝",
    "Beast": "野兽",
    "Construct": "结构体",
    "Insect": "昆虫",
    "Humanoid": "人形",
    "Formless": "无形",
    "Plant": "植物",
    "Earth": "地",
    "Water": "水",
    "Wind": "风",
    "Fire": "火",
    "Holy": "神圣",
    "Neutral": "自然",
    "Shadow": "暗影",
    "Upload save": "上传存档",
    "Upload Save": "上传存档",
    "Unlocked": "已解锁",
    "A cozy home": "一个舒适的家",
    "Basement": "地下室",
    "Commerce": "商业",
    "Consumption": "消耗",
    "Home": "家",
    "Leave Home": "离开家",
    "Sleep": "睡觉",
    "Workshop": "作坊",
    "Your current regeneration per tick:": "你当前每刻回复：",
    "The current date and time of the game, the format is y/m/d.": "当前游戏的日期和时间，格式为 年/月/日。",
    "Status Effects": "状态效果",
    "Mana Used:": "使用的法力:",
    "Scrolls Used:": "使用的卷轴:",
    "Required to cast magical spells.": "需要施放魔法咒语。",
    "One year in game is 4 months.": "游戏中的1年是4个月。",
    "One month in game is 28 days.": "游戏中的一个月是28天。",
    "Mana": "法力",
    "Magic": "魔法",
    "Locked": "未解锁",
    "Experience": "经验值",
    "Current experience:": "当前经验值:",
    "Earned mainly by fighting enemies. After reaching the required amount, you will level up, granting you bonus stats.": "主要通过与敌人战斗获得。在达到所需的数量后，您将升级，授予您额外的属性。",
    "Leave Workshop": "离开作坊",
    "Runecarving": "符文雕刻",
    "Plenty of space for crafting stations.": "有足够的空间来制作工作台。",
    "A good chunk of cooked meat. Tasty and filling.": "一个良好的煮熟的肉块。好吃又饱腹。",
    "A poor man's solution.": "一个穷人的解决方案。",
    "Cooked Meat": "煮熟的肉",
    "Cooked Rat Meat": "煮熟的老鼠肉",
    "Full of rats": "到处都是老鼠",
    "Kill some rats": "杀死一些老鼠",
    "Leave Basement": "离开地下室",
    "Rat": "老鼠",
    "Level Up": "升级了",
    "Get up": "起床",
    "Bed": "床",
    "Item acquired:": "获得物品：",
    "Rat has been slain": "老鼠已被击杀",
    "Warm bed": "温暖的床",
    "You have been knocked out.": "你被击倒了。",
    "Material": "材料",
    "Rat Meat": "老鼠肉",
    "Beggars can't be choosers. Although you should probably cook it first.": "乞丐不能挑肥拣瘦。不过你应该先把它煮熟。",
    "Bleeding Resistance": "流血抵抗",
    "Poison Resistance": "中毒抵抗",
    "Race": "种族",
    "Health": "生命值",
    "If this reaches zero, you wil get knocked out and saved by some random stranger that will drag you to your bed.": "如果这个值为0，你就会被打晕，然后被某个随机的陌生人救下，他会把你拖到床上。",
    "Reduces physical damage received (percentage).": "减少物理伤害（百分比）。",
    "Sleep until morning": "睡到天亮",
    "The bleeding resistance of the enemy. Reduced the amount you deal with bleeding (percentage).": "敌人的流血抵抗。减少你造成的出血伤害的数量（百分比）。",
    "The burning resistance of the enemy. Reduced the amount you deal with burning (percentage).": "敌人的燃烧抗性。减少你造成的燃烧伤害的数量（百分比）。",
    "The element of the enemy's armor. Affects damage dealt based on your weapon element or spell element.": "装甲：敌人盔甲的组成部分影响基于你的武器元素或法术元素造成的伤害。",
    "The element of the enemy's weapon. Affects damage received based on your armor element.": "敌人武器的组成部分。根据你的护甲元素影响受到的伤害。",
    "The poison resistance of the enemy. Reduced the amount you deal with poison (percentage).": "敌人对毒药的抵抗力。减少你造成的毒药的数量（百分比）。",
    "The race of the enemy. Affects damage dealt based on your hatred stat.": "敌人的种族。影响基于你的仇恨属性造成的伤害。",
    "Achievement": "成就",
    "Take 100 physical damage.": "受到100点物理伤害。",
    "Rat Tail": "鼠尾",
    "A rat tail. Yuck.": "一条老鼠尾巴。恶心。",
    "Import Save": "导入存档",
    "Import save": "导入存档",
    "Clicking this button will generate a save text into the text input next to it.": "单击此按钮将生成一个保存文本到它旁边的文本输入。",
    "Inputting a valid save text into the input next to this button and then pressing this button will set the game state to the state preserved in the save text.": "将有效的保存文本输入到此按钮旁边的输入中，然后按下此按钮将把游戏状态设置为保存文本中保留的状态。",
    "Selecting a valid save file in the input next to this button and then pressing this button will set the game state to the state preserved in the save file.": "在此按钮旁边的输入中选择一个有效的保存文件，然后按下此按钮将游戏状态设置为保存文件中保存的状态。",
    "This action cannot be undone, and it is recommended to create a backup first.": "该操作不可撤销，建议先创建备份。",
    "This save text can be imported below to return to this game state later, or it can be saved into a file as a backup.": "此保存文本可以在下面导入以稍后返回此游戏状态，或者可以将其保存到文件中作为备份。",
    "100 silver = 1 gold": "100 银币 = 1 金币",
    "100 copper = 1 silver": "100 铜币 = 1 银币",
    "100 gold = filthy rich": "100 金币 = 非常富有",
    "Money": "钱币",
    "Used to buy things.": "用来买东西。",
    "Adventurers' Guild": "冒险家行会",
    "City": "城市",
    "Craftsman district": "工匠区",
    "Enter Forest": "进入森林",
    "Illuminated by the moonlight.": "被月光照亮。",
    "Tower": "塔",
    "The Tower": "塔",
    "Training grounds": "训练场",
    "Training": "训练",
    "Train!": "训练!",
    "Training Dummy": "训练假人",
    "Train with Dummies": "用假人训练",
    "Cards": "卡片",
    "Elements": "元素",
    "Enchants": "附魔",
    "Therefore, not many people use runes, most just stick to scrolls. While expensive, it's less expensive than learning rune carving. And you also don't need to study the runestones themselves.": "因此，没有多少人使用符文，大多数人只是坚持使用卷轴。虽然很贵，但比学习符文雕刻要便宜。你也不需要研究符文石本身。",
    "Paying attention to elements is important. Elements are weak to some, while resistant against others. For example, attacking an enemy having fire armor with a fire attack will not be very effective, same goes for fire attack and water enemy.": "注意元素很重要。元素对某些元素是弱的，而对另一些元素是抵抗的。例如，用火力攻击攻击拥有火甲的敌人不会很有效，同样的道理也适用于火力攻击和水敌人。",
    "For those the tower also has an answer: magic! The first delvers found huge runestones on some of the floors. After further study they realized those runestones held secrets of actual magic!": "对这些人来说，这座塔也有一个答案：魔法！第一批运送者在一些地板上发现了巨大的符文石。经过进一步的研究，他们意识到这些符文石藏有真正魔法的秘密！",
    "Leave": "离开",
    "Leave Tower": "离开塔",
    "Making money": "赚钱",
    "Leave Training grounds": "离开训练场",
    "Leave Information board": "离开信息板",
    "Information board": "信息板",
    "Stay vigilant.": "保持警惕。",
    "Talk to the guards": "与守卫交谈",
    "While this might sound weird... since the tower appeared, people noticed forming strange attachment to the equipment they use the most, as if the equipment grows the more they use them or something...": "虽然这听起来很奇怪……自从塔出现以来，人们注意到他们对最常用的设备产生了奇怪的依恋，好像他们使用得越多，设备就会变大什么的……",
    "There is also the art of rune carving. You may, very rarely, find pieces of blank runestones in the tower. Someone with the spell knowledge and enough proficiency in rune carving may carve the spell into the rune.": "也有符文雕刻的艺术。你可能很少会在塔中找到空白的符文石。有符文知识和足够精通符文雕刻的人可能会把符文雕刻成符文。",
    "The main problem of runestones is that if you want to use them, you have to make them. If you want to make them, you need to practice on weaker spells first. And nobody else can use the products of your practice. Which makes the learning process extremely expensive.": "符文石的主要问题在于，如果你想使用它们，你就必须自己制造它们。如果你想制造它们，你需要先练习较弱的法术。没有人可以使用你的实践成果。这使得学习过程非常昂贵。",
    "Every attack and every armor has an elemental power behind it. Most mundane lifeforms have both attack and armor element of neutral. However, many enemies in the tower have different elements. For example fire slimes in the tower have fire element as their armor element.": "每一次攻击和每件盔甲背后都有一种元素力量。大多数世俗生命形态都有攻击和护甲元素。然而，塔中的许多敌人都有不同的元素。例如，塔上的火黏菌的护甲元素是火元素。",
    "Getting stronger": "变得更强",
    "Each runestone explains the secrets of using magic, specifically a single spell. After studying it completely, one can produce spell scrolls. Scrolls are a consumable item that allows one to cast the spell once. Anyone can use scrolls, but only those who studied the runestone can make them.": "每个符文石都解释了使用魔法的秘密，特别是一个咒语。学习完之后，就可以制作魔法卷轴了。卷轴是一种可消耗的道具，允许玩家使用一次法术。任何人都可以使用卷轴，但只有那些研究过符文石的人才能制作卷轴。",
    "Acquiring equipment": "获取装备",
    "(Attacking same element - fire vs fire: 0.25x)": "（攻击同一元素-火对火：0.25倍）",
    "(Attacking with strong element - fire vs earth: 1.5x)": "（使用强元素攻击-火对土：1.5倍）",
    "(Attacking with weak element - fire vs water: 0.5x)": "（攻击弱元素-火对水：0.5倍）",
    "(Fire > Earth > Wind > Water > Fire > ...)": "（火>土>风>水>火>…）",
    "(Holy and Shadow are each other's weakness, meaning holy vs shadow is 1.5x and shadow vs holy is 1.5x)": "（神圣和暗影是彼此的弱点，意味着神圣vs暗影是1.5倍，暗影vs神圣是1.5倍）",
    "(Neutral is not weak nor strong against anything)": "（中立既不是弱也不是强）",
    "Also, there is one important thing to remember. When you use an enchantment, it is consumed. Another enchantment can be used on the same item, but the original one will be lost.": "此外，有一件重要的事情要记住。当你使用魔法时，它会被消耗掉。另一种魔法可以用在同一件物品上，但原来的魔法会消失。",
    "Before entering, you should definitely visit the Training Grounds to learn a thing or two.": "在进入之前，你一定要去训练场学习一两件事。",
    "Bustling with activity": "热闹非凡",
    "By attempting to mimic the properties of cards, enchants were created.": "通过模仿卡片的属性，我们创造了魔法。",
    "Cards are items that can be very rarely obtained from enemies.": "卡牌是很少能从敌人那里获得的道具。",
    "Check the information board": "查看信息板",
    "Don't go directly to the requester, they will just turn you down....": "不要直接去找请求者，他们只会拒绝你....",
    "Every few days people around the city post their requests there.": "每隔几天，城市里的人们就会在那里发布他们的请求。",
    "Everyone is free to enter as they please, no requirements!": "每个人都可以自由进入，没有要求！",
    "First, they can only be used by the carver, seems like some kind of link is made when the carving happens.": "首先，它们只能由雕刻者使用，似乎在雕刻发生时形成了某种联系。",
    "Getting some equipment is not a bad idea either.": "买些装备也不是个坏主意。",
    "Hello there, if you want to enter, you are free to do so. We are here just to warn newcomers.": "你好，如果你想进入，你可以这么做。我们来这里只是为了警告新来的人。",
    "However, remember that cards get consumed when you use them. You can use another one on the same piece of equipment, but the previous card's effect will be lost.": "然而，请记住，当你使用卡片时，卡片会被消耗掉。你可以在同一件装备上使用另一张卡片，但前一张卡片的效果将会消失。",
    "However, they are much easier to craft than getting a card, so they are a cheap alternative, at least until you get lucky with a card.": "然而，它们比获得卡片更容易制作，所以它们是一种廉价的选择，至少在你幸运地获得一张卡片之前是如此。",
    "However, those who do use runes are... powerful. So powerful some people avoid them out of fear.": "然而，那些使用符文的人……强大。如此强大，一些人出于恐惧而避开它们。",
    "If you do not have money... well, tough luck!": "如果你没有钱……好吧，真倒霉！",
    "If you have the money, you can definitely grab something in the craftsman district.": "如果你有钱，你绝对可以在工匠区买到一些东西。",
    "In short, cards are good, great even.": "简而言之，纸牌很好，甚至很棒。",
    "It is said that every creature in the world may manifest a card and that every card is different.": "据说世界上的每一种生物都有一张卡片，每张卡片都是不同的。",
    "Most common inquiries are pinned here.": "大多数常见的问题都放在这里。",
    "Not only that, but the cards can also be used on your equipment to enchant them with special effects.": "不仅如此，卡牌还可以用在你的装备上，使它们具有特殊效果。",
    "Only some card effects were able to be replicated, and their efficiency was much lower than the cards themselves.": "只有一些卡片效果能够被复制，而且它们的效率远低于卡片本身。",
    "Same goes for you. You might find some rare armor that enchants you with an element. If you have fire armor, fire attack will do very little against you.": "你也一样。你可能会找到一些稀有的盔甲，用某种元素对你施了魔法。如果你有火焰护甲，那么火焰攻击对你的作用就很小了。",
    "Second, they are quite difficult to handle. It's hard to explain, but people can usually only activate one or two runes at the same time.": "其次，它们很难处理。这很难解释，但人们通常只能同时激活一两个符文。",
    "Simply do stuff, you will get better at what you are doing.": "简单地去做，你会在你做的事情上做得更好。",
    "Spell runes are permanent catalyst used to cast the carved spell. They are basically a permanent scroll. Although they come with some disadvantages.": "符文是永久的催化剂，用于施放雕刻的法术。它们基本上是一个永久的卷轴。尽管它们也有一些缺点。",
    "That's the reason we are all here, after all!": "毕竟，这就是我们在这里的原因！",
    "The best way to get money is to visit the Adventurers' Guild!": "获得金钱的最佳方式是访问冒险家公会！",
    "The field is full of unmoving training dummies.": "场地上全是一动不动的训练假人。",
    "The Guild handles everything. They inspect the goods you provide to ensure high quality and save the requester's time.": "公会处理一切。他们会检查您提供的货物，以确保高质量，并节省请求者的时间。",
    "The masters in crafting district might help you with that, either if they like you or you pay them.": "手工艺区的大师可能会帮助你，如果他们喜欢你或者你付钱给他们。",
    "The most straightforward is to fight enemies.": "最直接的是与敌人战斗。",
    "The recommendation is to get properly geared before thinking about it, though. Otherwise you might meet an early demise!": "不过，建议是在考虑这个问题之前做好适当的准备。否则你可能会早死！",
    "The top cannot be seen": "顶部看不见",
    "The top cannot be seen. A pair of guards stand near the entrance.": "顶部看不见。一对警卫站在入口处附近。",
    "The Tower is a place of endless opportunities, but also of endless dangers.": "伦敦塔是一个充满无限机会的地方，但也是一个充满无限危险的地方。",
    "They do come with two huge advantages though - they are permanent and they grow in power the more you use them.": "不过，它们确实有两个巨大的优势——它们是永久性的，而且你使用得越多，它们的威力就越大。",
    "They fight back!": "他们反击了！",
    "Third, they usually require more mana to use, the reason for that is unknown.": "第三，他们通常需要更多的魔法来使用，原因尚不清楚。",
    "Training Dummy has been slain!": "训练假人被击杀了！",
    "When you obtain a card of specific creature for the very first time, it is as if you have learned everything there is about the creature.": "当你第一次获得一张特定生物的卡牌时，就好像你已经了解了关于该生物的一切。",
    "Where the useless become less useless (hopefully)": "让无用变得不那么无用（希望如此）",
    "While most people love money and are attracted by the profits possible only by climbing the tower, there are those who have no interest in worldly possessions.": "虽然大多数人都爱钱，并被攀上高塔可能带来的利润所吸引，但也有一些人对世俗的财富不感兴趣。",
    "With magic comes the importance of elements.": "魔法带来了元素的重要性。",
    "You can make something yourself, but you would have to be proficient in crafting first. And you would also need to have the proper crafting station.": "你可以自己制作一些东西，但你必须首先精通手工制作。你还需要有适当的工艺站。",
    "You can start with the dummies here or if you are felling confident, you can try the nearby woods.": "你可以从这里的假人开始，如果你有信心的话，你可以试试附近的树林。",
    "You should also visit the Adventurers' Guild, complete some jobs to get some money and properly equip yourself.": "你也应该访问冒险家公会，完成一些工作来获得一些钱和适当的装备自己。",
    "You should spend ample time in the Training Ground and the nearby woods, first.": "首先，你应该花足够的时间在训练场和附近的树林里。",
    "You simply gather the items requested and then hand it over at the Reception in the Guild.": "你只需收集所需的物品，然后在公会的接待处交给他们。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Poison Bite": "毒咬",
    "Ouch!": "哎哟!",
    "First Blood": "第一滴血",
    "A:": "攻击:",
    "W:": "武器:",
    "R:": "种族:",
    "BUR:": "燃烧抵抗:",
    "BLR:": "流血抵抗:",
    "PR:": "中毒抵抗:",
    "HP:": "生命值:",
    "MP:": "法力值:",
    "DEF": "防御",
    "DEX": "灵巧",
    "STR": "力量",
    "INT": "智力",
    "QTY": "数量",
    "DR": "伤害减免",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "ABC": "ABC",
    "Monday": "周一",
    "Tuesday": "周二",
    "Wednesday": "周三",
    "Thursday": "周四",
    "Friday": "周五",
    "Saturday": "周六",
    "Sunday": "周日",
    ":": ":",
    ", ": ", ",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需造成的的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Player": "玩家",
    "Critical chance: ": "暴击率: ",
    "Value: ": "值: ",
    " Prof.": "教授",
    "Increases the damage you deal against enemies of the ": "增加你对 ",
    "Increases the damage you deal against enemies with ": "增加你对 ",
    "Increases the damage you deal with ": "增加你对 ",
    "Unlocked: ": "已解锁: ",
    "Duration: ": "持续时间: ",
    "Basement: ": "地下室: ",
    " hit Rat for ": " 对 老鼠 造成伤害 ",
    " hit Training Dummy for ": " 对 训练假人 造成伤害 ",
    "EXP + ": "经验值 + ",
    "New achievement unlocked! ": "新成就解锁了! ",
    "Rat hit Player for ": "老鼠 击中了 玩家 并造成伤害 ",
    "Rat used ": "老鼠使用了 ",
    "<": "<",
    "Training Grounds: ": "训练场: ",
    "Training Dummy hit Player for ": "训练假人 击中 玩家 并造成伤害 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需造成的的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " race. Each point equals 1% damage increase.": " 种族敌人造成的伤害。每增加1点相当于增加1%的伤害。",
    " element. Each point equals 1% damage increase.": " 元素敌人造成的伤害。每增加1点相当于增加1%的伤害。",
    " attacks. Each point equals 1% damage increase.": " 攻击敌人造成的伤害。每增加1点相当于增加1%的伤害。",
    ",": ",",
    ">": ">",
    "!": "!",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\%.$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)\/([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+). ([\d\.,]+). ([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) mana \+ ([\d\.]+)\% maximum mana$/, '$1 法力 + $2\% 法力值上限'],
    [/^([\d\.]+) health \+ ([\d\.]+)\% maximum health$/, '$1 生命值 + $2\% 生命值上限'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^STR \+ ([\d\.,]+), INT \+ ([\d\.,]+), Max HP \+ ([\d\.,]+), Max MP \+ ([\d\.,]+)!$/, '力量 + $1, 智力 + $2, 生命值上限 + $3, 法力值上限 + $4!'],
    [/^\(([\d\.,]+) seconds\)$/, '($1 秒)'],
    [/^Level: ([\d\.,]+) \| Exp: (.+)$/, '等级: $1 \| 经验值: $2'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Tenacity has reached level ([\d\.,]+)$/, '坚韧达到了 $1 级'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);