/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类: 
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal": "目标",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently": "当前",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord": "加入 Discord",
    "Credits": "鸣谢",
    "Hidden": "隐藏",
    "Heirloom": "传家宝",
    "Item": "物品",
    "Other": "其他",
    "Etc": "其它",
    "Log": "日志",
    "Monday": "周一",
    "Tuesday": "周二",
    "Skills": "技能",
    "Start Journey": "开始旅程",
    "Type": "类型",
    "Tooltip": "工具提示",
    "Use": "使用",
    "World Navigation": "世界导航",
    "Enchant": "附魔",
    "Equipment": "装备",
    "Equip": "装备",
    "Combat": "战斗",
    "Action Window": "行动窗口",
    "(Icons)": "(图标)",
    "(Battlers)": "(战士)",
    ". This happens and is explained in full after finishing floor 1 of the tower. It is recommended not to protract the first run before getting there and fully understanding this mechanic.": "．这是在完成塔的第一层后发生的。在完全理解这一机制之前，建议不要延长第一次运行时间。",
    "Yes, filling your belly would be a good start.": "是的，填饱肚子是个好的开始。",
    "Welcome to the Climb, if you see/hear this, you are using a screenreader. This game is unfortunately not made with people like you in mind, I am sorry. However, I did do some tweaks to at least enable you to play somewhat. The most important thing is knowing that \"mouse over\" is extremely important in this game. Crucial information is displayed when you \"mouse over\" things, like, but not limited to, inventory. If you find a \"clickable\", it most likely has a tooltip. There is a tooltip element that exists near the bottom of the page, it is marked by a heading level 2. This element is updated whenever you mouse over something that does have a tooltip. Once again I am sorry for not being able to spend more time making the game more accessible, but I do hope you have fun with the limited functionality available. If you think there are some minor tweaks that would make the experience more enjoyable to play, let me know on discord.": "欢迎来到攀登，如果你看到/听到这个，你正在使用屏幕阅读器。不幸的是，这个游戏并没有考虑到像你这样的人，我很抱歉。然而，我确实做了一些调整，至少让你能玩一些。最重要的是要知道“鼠标悬停”在这个游戏中是非常重要的。当你“鼠标移到”物品上时，关键信息就会显示出来，比如，但不限于，库存。如果你发现一个“可点击的”，它很可能有一个工具提示。在页面底部附近有一个工具提示元素，它被标记为标题级别2。当您将鼠标移到有工具提示的东西上时，此元素就会更新。我再次为不能花更多时间让游戏更容易上手而感到抱歉，但我希望你能在有限的功能中玩得开心。如果你认为有一些小的调整可以让游戏体验更愉快，请在Discord上告诉我。",
    "The game was not designed for small devices such as mobile phones. Text may be hard to read and hover tooltips hard to access. This includes important gameplay explanations, lore and questlines. It is strongly recommended to play the game on a desktop or a laptop instead..": "这款游戏不是为手机等小型设备设计的。文本可能难以阅读，悬停工具提示难以访问。这包括重要的游戏玩法解释，传说和任务线。强烈建议在台式机或笔记本电脑上玩此游戏。",
    "A long journey lies ahead.": "前面还有很长的路要走。",
    "Aekashics": "美学",
    "And living among these brave heroes is you, a nobody. A nobody with a dream - to conquer the tower. Or at least earn enough to fill your belly.": "而你，一个无名小卒，生活在这些勇敢的英雄之中。一个没有梦想的无名小卒——征服高塔。或者至少赚到足够填饱肚子的钱。",
    "And then you should probably check around the Training Grounds in the City.": "然后你应该去城里的训练场看看。",
    "Brought to you by Motas.": "由Motas为您带来。",
    "Clockwork Raven": "发条乌鸦",
    "Everyone who provided feedback and suggestions": "所有提供反馈和建议的人",
    "finalbossblues": "finalbossblues",
    "Full of monster, but also treasures, it attracted countless adventurers, and a bustling city was built around it.": "充满了怪物，也有宝藏，它吸引了无数的冒险家，并在它周围建立了一个繁华的城市。",
    "Information Window": "信息窗口",
    "Inventory": "库存",
    "It has been 500 years since the Tower appeared.": "自从塔出现以来，已经有500年了。",
    "Join us on discord": "加入我们的Discord吧",
    "Journal": "日记",
    "MDEF": "魔法防御",
    "Neutral": "中立",
    "Pipoya": "Pipoya",
    "Status": "状态",
    "Thank you for playing": "谢谢你的参与",
    "The Beginning": "开始",
    "The tower pierces through the heavens, its top nowhere to be seen.": "这座塔高耸入云，看不到塔顶。",
    "There are new quests available in the Adventurers' Guild.": "在冒险家公会中有新的任务。",
    "This game features a prestige mechanic, meaning it resets parts of your progress": "这款游戏的特色是声望机制，这意味着它会重置你的部分进度",
    "This is a demo with limited content.": "这是一个内容有限的演示。",
    "Unremarkable": "平平无奇",
    "Vitals": "生命值",
    " Stats": "属性",
    ": Press shift to show controls overlay, this allows you to set item as favorite, hide it into the hidden tab, delete it and later in the game - feed it. Use right click on inventory filters to use them as toggles instead of tabs.": ": 按shift显示控件覆盖，这可以让你设置物品为收藏，隐藏到隐藏标签，删除它，后来在游戏中提供它。在库存过滤器上使用右键将它们用作开关而不是选项卡。",
    ": Some actions will remove equipment from your inventory (completing quests, feeding). These actions only count and remove clean equipment. An equipment is clean when it has no experience, no rank, no socketed enchant (or card) and is not an heirloom (except runes), equipped, favorite or hidden. It's basically a new piece of equipment you have not interacted with.": ": 一些动作会从你的库存中移除装备（完成任务，喂养）。这些动作只计算和移除干净的装备。当一个装备没有经验，没有等级，没有嵌套的附魔（或卡牌），不是传家宝（除了符文），装备，最爱或隐藏时，它就是干净的。它基本上是一个你没有与之互动的新装备。",
    "Pause": "暂停",
    "Pauses the game.": "暂停游戏。",
    "intelligence": "智力",
    "Intelligence": "智力",
    "Dark Mode": "深色模式",
    "Removes": "移除",
    "Quests": "任务",
    "Poison": "药水",
    "Save Export": "导出存档",
    "strength": "力量",
    "Strength": "力量",
    "Updates": "更新",
    "Weapon Element": "武器元素",
    "Travelers": "旅行者",
    "Traveler": "旅行者",
    "Your progress is saved.": "您的游戏进度已保存。",
    "Burning": "燃烧",
    "Bleeding": "流血",
    "Bestiary": "图鉴",
    "Bandage": "绷带",
    "Armor Element": "护甲元素",
    "About": "关于",
    "Clean items": "清理物品",
    ": Pressing 0-9 while hovering over an item allows you to set a hotkey. Using the hotkey uses the item. You can also hold the hotkey for rapid usage.": ": 当鼠标悬停在一个项目上时按0-9键可以设置一个热键。使用热键可以使用该项。也可以按住热键快速使用。",
    "A jug of enchanted water, effective at dousing basic magical fire.": "一壶施了魔法的水，能有效地扑灭基本的魔法火焰。",
    "A piece of dry bread. Somewhat filling, no risk of food poisoning, cheap. Nothing to complain about, right? Right?": "一块干面包。有点饱腹感，没有食物中毒的风险，便宜。没什么好抱怨的，对吧？对吧?",
    "Alternatively, you can press and hold the shift key.": "或者，您也可以按住shift键。",
    "Antidote": "解药",
    "Check out what's new": "看看有什么新消息",
    "Click this icon to remove the golden highlight.": "单击此图标以移除金色高光。",
    "Click this to export your save into a text file.": "单击此按钮将您的保存导出为文本文件。",
    "Click to toggle.": "单击进行切换。",
    "Cloth bandage, effective at stopping bleeding.": "布绷带，止血效果好。",
    "Food": "食物",
    "Medicine": "药品",
    "Controls": "控制",
    "Damage Reduction": "伤害减免",
    "damage reduction": "伤害减免",
    "dexterity": "灵巧",
    "Dexterity": "灵巧",
    "Dims the background.": "调暗背景。",
    "Dry Bread": "干面包",
    "Enchanted Water": "附魔之水",
    "Equipment": "装备",
    "HP Regeneration": "生命回复",
    "Increase magical damage dealt.": "增加魔法伤害。",
    "Increase physical damage dealt.": "增加物理伤害。",
    "Increases critical chance.": "增加暴击几率。",
    "Inventory Guide": "库存指南",
    "Learned Diagrams": "学习图表",
    "magical defense": "魔法防御",
    "Magical Defense": "魔法防御",
    "Mixture of medicinal ingredients, effective at stopping most poisons.": "混合的药物成分，有效地阻止大多数毒药。",
    "Normal Speed": "正常速度",
    "Opens the about overlay.": "打开关于弹出层。",
    "Opens the inventory controls. Click again to close.": "打开库存控制。再次单击关闭。",
    "Opens the settings overlay.": "打开设置弹出层。",
    "Opens the updates overlay.": "打开更新弹出层。",
    "Reduces all damage received (flat amount).": "减少所有伤害（固定数量）。",
    "Reduces magical damage received (percentage).": "减少魔法伤害（百分比）。",
    "Runs the game at normal speed.": "以正常速度运行游戏。",
    "The element of your armor. Affects damage received based on enemy weapon element.": "你护甲的元素。根据敌人的武器元素影响受到的伤害。",
    "The element of your weapon. Affects damage dealt based on enemy armor element.": "你武器的元素。影响对敌方护甲造成的伤害。",
    "Reset Game": "重置游戏",
    "Drinks Consumed": "消耗的饮料",
    "Death Count": "死亡次数",
    "Cards Obtained": "获得的卡片",
    "Water Killed": "水击杀",
    "Races Killed": "种族击杀",
    "Neutral Killed": "中立击杀",
    "Formless Killed": "无形击杀",
    "Enemies Killed": "击杀的敌人",
    "Construct Killed": "结构击杀",
    "Bosses Killed": "击杀的Boss",
    "Burning Damage Dealt": "造成的燃烧伤害",
    "Bleeding Damage Dealt": "造成的流血伤害",
    "Bleeding Damage Received": "受到的流血伤害",
    "Burning Resistance": "火焰抵抗",
    "Combat Mastery Exp": "战斗精通经验值",
    "Alchemy Exp": "炼金术经验值",
    "Blacksmithing Exp": "锻造经验值",
    "Trading Exp": "交易经验值",
    "Enchanting Exp": "附魔经验值",
    "Chronomancy Exp": "时卜术经验值",
    "Tailoring Exp": "裁剪经验值",
    "Cooking Exp": "烹饪经验值",
    "Water Affinity Exp": "水系亲和经验值",
    "Date and Time": "日期和时间",
    "Defense": "防御",
    "discord link": "Discord链接",
    "Discount": "折扣",
    "Discount now applies on workstation purchases": "折扣现在适用于购买工作站",
    "Damage Received": "受到的伤害",
    "Damage Dealt": "造成的伤害",
    "Crit Power": "暴击伤害",
    "Cooking": "烹饪",
    "Drop Rate": "掉落率",
    "Enchanting": "附魔",
    "Elements Killed": "击杀的元素",
    "Generate save": "生成存档",
    "Generate Save": "生成存档",
    "General": "常规",
    "Spells Cast": "施放的法术",
    "Tailoring": "裁剪",
    "Beast": "野兽",
    "Construct": "结构体",
    "Insect": "昆虫",
    "Humanoid": "人形",
    "Formless": "无形",
    "Plant": "植物",
    "earth": "土",
    "Earth": "土",
    "Water": "水",
    "water": "水",
    "Wind": "风",
    "wind": "风",
    "Fire": "火",
    "fire": "火",
    "Holy": "神圣",
    "Neutral": "中立",
    "Shadow": "暗影",
    "Upload save": "上传存档",
    "Upload Save": "上传存档",
    "Unlocked": "已解锁",
    "A cozy home": "一个舒适的家",
    "Basement": "地下室",
    "Commerce": "商业",
    "Consumption": "消耗",
    "Home": "家",
    "Sleep": "睡觉",
    "Workshop": "作坊",
    "Your current regeneration per tick": "你当前每刻回复: ",
    "The current date and time of the game, the format is y/m/d.": "当前游戏的日期和时间，格式为 年/月/日。",
    "Status Effects": "状态效果",
    "Mana Used": "使用的法力",
    "Scrolls Used": "使用的卷轴",
    "Required to cast magical spells.": "需要施放魔法咒语。",
    "One year in game is 4 months.": "游戏中的1年是4个月。",
    "One month in game is 28 days.": "游戏中的一个月是28天。",
    "mana": "法力",
    "Mana": "法力",
    "Magic": "魔法",
    "Locked": "未解锁",
    "Experience": "经验值",
    "Current experience": "当前经验值",
    "Earned mainly by fighting enemies. After reaching the required amount, you will level up, granting you bonus stats.": "主要通过与敌人战斗获得。在达到所需的数量后，您将升级，授予您额外的属性。",
    "Runecarving": "符文雕刻",
    "Plenty of space for crafting stations.": "有足够的空间来制作工作台。",
    "A good chunk of cooked meat. Tasty and filling.": "一个良好的煮熟的肉块。好吃又饱腹。",
    "A poor man's solution.": "一个穷人的解决方案。",
    "Cooked Meat": "煮熟的肉",
    "Cooked Rat Meat": "煮熟的老鼠肉",
    "Full of rats": "到处都是老鼠",
    "Kill some rats": "杀死一些老鼠",
    "Rat": "老鼠",
    "Level Up": "升级了",
    "Get up": "起床",
    "Bed": "床",
    "Item acquired": "获得物品: ",
    "Warm bed": "温暖的床",
    "You have been knocked out.": "你被击倒了。",
    "Material": "材料",
    "Rat Meat": "老鼠肉",
    "Beggars can't be choosers. Although you should probably cook it first.": "乞丐不能挑肥拣瘦。不过你应该先把它煮熟。",
    "Bleeding Resistance": "流血抵抗",
    "Poison Resistance": "中毒抵抗",
    "Race": "种族",
    "health": "生命值",
    "Health": "生命值",
    "If this reaches zero, you wil get knocked out and saved by some random stranger that will drag you to your bed.": "如果这个值为0，你就会被打晕，然后被某个随机的陌生人救下，他会把你拖到床上。",
    "Reduces physical damage received (percentage).": "减少物理伤害（百分比）。",
    "Sleep until morning": "睡到天亮",
    "The bleeding resistance of the enemy. Reduced the amount you deal with bleeding (percentage).": "敌人的流血抵抗。减少你造成的出血伤害的数量（百分比）。",
    "The burning resistance of the enemy. Reduced the amount you deal with burning (percentage).": "敌人的燃烧抗性。减少你造成的燃烧伤害的数量（百分比）。",
    "The element of the enemy's armor. Affects damage dealt based on your weapon element or spell element.": "装甲: 敌人护甲的组成部分影响基于你的武器元素或法术元素造成的伤害。",
    "The element of the enemy's weapon. Affects damage received based on your armor element.": "敌人武器的组成部分。根据你的护甲元素影响受到的伤害。",
    "The poison resistance of the enemy. Reduced the amount you deal with poison (percentage).": "敌人对毒药的抵抗力。减少你造成的毒药的数量（百分比）。",
    "The race of the enemy. Affects damage dealt based on your hatred stat.": "敌人的种族。影响基于你的仇恨属性造成的伤害。",
    "Achievement": "成就",
    "Take 100 physical damage.": "受到100点物理伤害。",
    "Rat Tail": "鼠尾",
    "A rat tail. Yuck.": "一条老鼠尾巴。恶心。",
    "Import Save": "导入存档",
    "Import save": "导入存档",
    "Clicking this button will generate a save text into the text input next to it.": "单击此按钮将生成一个保存文本到它旁边的文本输入。",
    "Inputting a valid save text into the input next to this button and then pressing this button will set the game state to the state preserved in the save text.": "将有效的保存文本输入到此按钮旁边的输入中，然后按下此按钮将把游戏状态设置为保存文本中保留的状态。",
    "Selecting a valid save file in the input next to this button and then pressing this button will set the game state to the state preserved in the save file.": "在此按钮旁边的输入中选择一个有效的保存文件，然后按下此按钮将游戏状态设置为保存文件中保存的状态。",
    "This action cannot be undone, and it is recommended to create a backup first.": "该操作不可撤销，建议先创建备份。",
    "This save text can be imported below to return to this game state later, or it can be saved into a file as a backup.": "此保存文本可以在下面导入以稍后返回此游戏状态，或者可以将其保存到文件中作为备份。",
    "100 silver = 1 gold": "100 银币 = 1 金币",
    "100 copper = 1 silver": "100 铜币 = 1 银币",
    "100 gold = filthy rich": "100 金币 = 非常富有",
    "Money": "钱币",
    "Used to buy things.": "用来买东西。",
    "Adventurers' Guild": "冒险家行会",
    "City": "城市",
    "Craftsman district": "工匠区",
    "Enter Forest": "进入森林",
    "Illuminated by the moonlight.": "被月光照亮。",
    "Tower": "塔",
    "The Tower": "塔",
    "Training grounds": "训练场",
    "Training": "训练",
    "Train": "训练",
    "Training Dummy": "训练假人",
    "Train with Dummies": "用假人训练",
    "Cards": "卡片",
    "Elements": "元素",
    "Enchants": "附魔",
    "Therefore, not many people use runes, most just stick to scrolls. While expensive, it's less expensive than learning rune carving. And you also don't need to study the runestones themselves.": "因此，没有多少人使用符文，大多数人只是坚持使用卷轴。虽然很贵，但比学习符文雕刻要便宜。你也不需要研究符文石本身。",
    "Paying attention to elements is important. Elements are weak to some, while resistant against others. For example, attacking an enemy having fire armor with a fire attack will not be very effective, same goes for fire attack and water enemy.": "注意元素很重要。元素对某些元素是弱的，而对另一些元素是抵抗的。例如，用火力攻击攻击拥有火甲的敌人不会很有效，同样的道理也适用于火力攻击和水敌人。",
    "For those the tower also has an answer: magic! The first delvers found huge runestones on some of the floors. After further study they realized those runestones held secrets of actual magic": "对这些人来说，这座塔也有一个答案: 魔法！第一批运送者在一些楼层上发现了巨大的符文石。经过进一步的研究，他们意识到这些符文石藏有真正魔法的秘密",
    "Leave": "离开",
    "Making money": "赚钱",
    "Information board": "信息板",
    "Stay vigilant.": "保持警惕。",
    "Talk to the guards": "与守卫交谈",
    "While this might sound weird... since the tower appeared, people noticed forming strange attachment to the equipment they use the most, as if the equipment grows the more they use them or something...": "虽然这听起来很奇怪……自从塔出现以来，人们注意到他们对最常用的设备产生了奇怪的依恋，好像他们使用得越多，设备就会变大什么的……",
    "There is also the art of rune carving. You may, very rarely, find pieces of blank runestones in the tower. Someone with the spell knowledge and enough proficiency in rune carving may carve the spell into the rune.": "也有符文雕刻的艺术。你可能很少会在塔中找到空白的符文石。有符文知识和足够精通符文雕刻的人可能会把符文雕刻成符文。",
    "The main problem of runestones is that if you want to use them, you have to make them. If you want to make them, you need to practice on weaker spells first. And nobody else can use the products of your practice. Which makes the learning process extremely expensive.": "符文石的主要问题在于，如果你想使用它们，你就必须自己制造它们。如果你想制造它们，你需要先练习较弱的法术。没有人可以使用你的实践成果。这使得学习过程非常昂贵。",
    "Every attack and every armor has an elemental power behind it. Most mundane lifeforms have both attack and armor element of neutral. However, many enemies in the tower have different elements. For example fire slimes in the tower have fire element as their armor element.": "每一次攻击和每件护甲背后都有一种元素力量。大多数普通生命形态的攻击和护甲元素都是中立的。然而，塔中的许多敌人都有不同的元素。例如，塔上的火黏菌的护甲元素是火元素。",
    "Getting stronger": "变得更强",
    "Each runestone explains the secrets of using magic, specifically a single spell. After studying it completely, one can produce spell scrolls. Scrolls are a consumable item that allows one to cast the spell once. Anyone can use scrolls, but only those who studied the runestone can make them.": "每个符文石都解释了使用魔法的秘密，特别是一个咒语。学习完之后，就可以制作魔法卷轴了。卷轴是一种可消耗的道具，允许玩家使用一次法术。任何人都可以使用卷轴，但只有那些研究过符文石的人才能制作卷轴。",
    "Acquiring equipment": "获取装备",
    "(Attacking same element - fire vs fire: 0.25x)": "（攻击同一元素-火对火: 0.25倍）",
    "(Attacking with strong element - fire vs earth: 1.5x)": "（使用强元素攻击-火对土: 1.5倍）",
    "(Attacking with weak element - fire vs water: 0.5x)": "（攻击弱元素-火对水: 0.5倍）",
    "(Fire > Earth > Wind > Water > Fire > ...)": "（火>土>风>水>火>…）",
    "(Holy and Shadow are each other's weakness, meaning holy vs shadow is 1.5x and shadow vs holy is 1.5x)": "（神圣和暗影是彼此的弱点，意味着神圣vs暗影是1.5倍，暗影vs神圣是1.5倍）",
    "(Neutral is not weak nor strong against anything)": "（中立既不是弱也不是强）",
    "Also, there is one important thing to remember. When you use an enchantment, it is consumed. Another enchantment can be used on the same item, but the original one will be lost.": "此外，有一件重要的事情要记住。当你使用魔法时，它会被消耗掉。另一种魔法可以用在同一件物品上，但原来的魔法会消失。",
    "Before entering, you should definitely visit the Training Grounds to learn a thing or two.": "在进入之前，你一定要去训练场学习一两件事。",
    "Bustling with activity": "热闹非凡",
    "By attempting to mimic the properties of cards, enchants were created.": "通过模仿卡片的属性，我们创造了魔法。",
    "Cards are items that can be very rarely obtained from enemies.": "卡牌是很少能从敌人那里获得的道具。",
    "Check the information board": "查看信息板",
    "Don't go directly to the requester, they will just turn you down....": "不要直接去找请求者，他们只会拒绝你....",
    "Every few days people around the city post their requests there.": "每隔几天，城市里的人们就会在那里发布他们的请求。",
    "Everyone is free to enter as they please, no requirements": "每个人都可以自由进入，没有要求",
    "First, they can only be used by the carver, seems like some kind of link is made when the carving happens.": "首先，它们只能由雕刻者使用，似乎在雕刻发生时形成了某种联系。",
    "Getting some equipment is not a bad idea either.": "买些装备也不是个坏主意。",
    "Hello there, if you want to enter, you are free to do so. We are here just to warn newcomers.": "你好，如果你想进入，你可以这么做。我们来这里只是为了警告新来的人。",
    "However, remember that cards get consumed when you use them. You can use another one on the same piece of equipment, but the previous card's effect will be lost.": "然而，请记住，当你使用卡片时，卡片会被消耗掉。你可以在同一件装备上使用另一张卡片，但前一张卡片的效果将会消失。",
    "However, they are much easier to craft than getting a card, so they are a cheap alternative, at least until you get lucky with a card.": "然而，它们比获得卡片更容易制作，所以它们是一种廉价的选择，至少在你幸运地获得一张卡片之前是如此。",
    "However, those who do use runes are... powerful. So powerful some people avoid them out of fear.": "然而，那些使用符文的人……强大。如此强大，一些人出于恐惧而避开它们。",
    "If you do not have money... well, tough luck": "如果你没有钱……好吧，真倒霉",
    "If you have the money, you can definitely grab something in the craftsman district.": "如果你有钱，你绝对可以在工匠区买到一些东西。",
    "In short, cards are good, great even.": "简而言之，纸牌很好，甚至很棒。",
    "It is said that every creature in the world may manifest a card and that every card is different.": "据说世界上的每一种生物都有一张卡片，每张卡片都是不同的。",
    "Most common inquiries are pinned here.": "大多数常见的问题都放在这里。",
    "Not only that, but the cards can also be used on your equipment to enchant them with special effects.": "不仅如此，卡牌还可以用在你的装备上，使它们具有特殊效果。",
    "Only some card effects were able to be replicated, and their efficiency was much lower than the cards themselves.": "只有一些卡片效果能够被复制，而且它们的效率远低于卡片本身。",
    "Same goes for you. You might find some rare armor that enchants you with an element. If you have fire armor, fire attack will do very little against you.": "你也一样。你可能会找到一些稀有的护甲，用某种元素对你施了魔法。如果你有火焰护甲，那么火焰攻击对你的作用就很小了。",
    "Second, they are quite difficult to handle. It's hard to explain, but people can usually only activate one or two runes at the same time.": "其次，它们很难处理。这很难解释，但人们通常只能同时激活一两个符文。",
    "Simply do stuff, you will get better at what you are doing.": "简单地去做，你会在你做的事情上做得更好。",
    "Spell runes are permanent catalyst used to cast the carved spell. They are basically a permanent scroll. Although they come with some disadvantages.": "符文是永久的催化剂，用于施放雕刻的法术。它们基本上是一个永久的卷轴。尽管它们也有一些缺点。",
    "That's the reason we are all here, after all": "毕竟，这就是我们在这里的原因",
    "The best way to get money is to visit the Adventurers' Guild": "获得金钱的最佳方式是访问冒险家公会",
    "The field is full of unmoving training dummies.": "场地上全是一动不动的训练假人。",
    "The Guild handles everything. They inspect the goods you provide to ensure high quality and save the requester's time.": "公会处理一切。他们会检查您提供的货物，以确保高质量，并节省请求者的时间。",
    "The masters in crafting district might help you with that, either if they like you or you pay them.": "手工艺区的大师可能会帮助你，如果他们喜欢你或者你付钱给他们。",
    "The most straightforward is to fight enemies.": "最直接的是与敌人战斗。",
    "The recommendation is to get properly geared before thinking about it, though. Otherwise you might meet an early demise": "不过，建议是在考虑这个问题之前做好适当的准备。否则你可能会早死",
    "The top cannot be seen": "顶部看不见",
    "The top cannot be seen. A pair of guards stand near the entrance.": "顶部看不见。一对警卫站在入口处附近。",
    "The Tower is a place of endless opportunities, but also of endless dangers.": "伦敦塔是一个充满无限机会的地方，但也是一个充满无限危险的地方。",
    "They do come with two huge advantages though - they are permanent and they grow in power the more you use them.": "不过，它们确实有两个巨大的优势——它们是永久性的，而且你使用得越多，它们的威力就越大。",
    "They fight back": "他们反击了",
    "Third, they usually require more mana to use, the reason for that is unknown.": "第三，他们通常需要更多的魔法来使用，原因尚不清楚。",
    "When you obtain a card of specific creature for the very first time, it is as if you have learned everything there is about the creature.": "当你第一次获得一张特定生物的卡牌时，就好像你已经了解了关于该生物的一切。",
    "Where the useless become less useless (hopefully)": "让无用变得不那么无用（希望如此）",
    "While most people love money and are attracted by the profits possible only by climbing the tower, there are those who have no interest in worldly possessions.": "虽然大多数人都爱钱，并被攀上高塔可能带来的利润所吸引，但也有一些人对世俗的财富不感兴趣。",
    "With magic comes the importance of elements.": "魔法带来了元素的重要性。",
    "You can make something yourself, but you would have to be proficient in crafting first. And you would also need to have the proper crafting station.": "你可以自己制作一些东西，但你必须首先精通手工制作。你还需要有适当的工艺站。",
    "You can start with the dummies here or if you are felling confident, you can try the nearby woods.": "你可以从这里的假人开始，如果你有信心的话，你可以试试附近的树林。",
    "You should also visit the Adventurers' Guild, complete some jobs to get some money and properly equip yourself.": "你也应该访问冒险家公会，完成一些工作来获得一些钱和适当的装备自己。",
    "You should spend ample time in the Training Ground and the nearby woods, first.": "首先，你应该花足够的时间在训练场和附近的树林里。",
    "You simply gather the items requested and then hand it over at the Reception in the Guild.": "你只需收集所需的物品，然后在公会的接待处交给他们。",
    "That was a good session": "那是一个很好的会议",
    "Neutral Hatred": "中立仇恨",
    "Train until you drop": "训练直到你倒下",
    "Herb": "草药",
    "Buy": "购买",
    "Bar": "酒吧",
    "Y'know younglings *hic*. In my time, they'd all rush over to the *hic* tower. getting as many blessing as fast as they can. *hic* Tis not the same anymore, people only waste time trying to shoot for the *hic* stars now. Don't be like 'em younglings, snatch that blessin' soon as you can. *hic* You'll thank me later.": "你知道那些年轻人。在我那个年代，他们都会冲到那个“怪”塔上去。尽快得到尽可能多的祝福。现在不一样了，人们只会把时间浪费在追逐明星上。不要像那些年轻人一样，尽快抓住那份祝福。你以后会感谢我的。",
    ". This happens and is explained in full after finishing floor 1 of the tower. It is recommended not to protract the first run before getting there and fully understanding this mechanic.)": "。这是在完成塔的第一层后发生的。在完全理解这一机制之前，建议不要延长第一次运行时间。)",
    ", you will gain 100% more Cooking experience for 300 seconds.": "，你将获得100%的烹饪经验，持续300秒。",
    ". Upon using": "。使用时",
    "(You have been warned about the prestige mechanic, if you skimmed through it, check Journal -> Travelers -> Polus)": "（你已经被警告过声望机制，如果你浏览了一下，请查看 旅程 -> 旅行者 -> 波洛斯）",
    "*After finishing his grumble, he falls flat on the ground, asleep*": "抱怨完之后，他趴在地上睡着了",
    "*As you enter the building, you see a drunk stumbling around mumbling something*": "当你进入大楼时，你看到一个醉汉跌跌撞撞地走来走去，嘴里喃喃自语",
    "A fat man stands behind the bar": "一个胖子站在吧台后面",
    "A large wooden board with requests pinned up.": "一块钉着请求的大木板。",
    "Check job board": "检查求职板",
    "Chef's rat meat": "厨师的老鼠肉",
    "Clean water, refreshing.": "干净的水，令人耳目一新。",
    "Drink": "饮料",
    "Cooking manual": "烹饪手册",
    "Cooking Theory": "烹饪理论",
    "Cooksta": "库克斯塔",
    "Crakon": "克拉肯",
    "Crakon's herbs": "克拉肯的草药",
    "Crakon's need for rat tails": "克拉肯需要老鼠尾巴",
    "Crakon's Potions": "克拉肯的药水",
    "Crakon's Potions Assortment": "克拉肯的药水分类",
    "Devon": "德文",
    "Devon's Anvil": "德文铁砧",
    "Devon's training equipment": "德文的训练装备",
    "Failure Consequences": "失败的后果",
    "Feather": "羽毛",
    "Finish job requests": "完成工作要求",
    "Grants": "获得",
    "Holer's Enchants": "霍尔的附魔",
    "Holer": "霍尔",
    "I am low on basic herbs. Any herb-pickers around?": "我缺少基本的草药。附近有采摘草药的人吗？",
    "I am offering a monetary reward and some refreshments to anyone who trains hard. Bring me some twigs as a proof.": "我将提供金钱奖励和一些茶点给任何努力训练的人。给我拿些树枝来证明。",
    "I am running low on feathers for arrows. It would be great if someone could get me some.": "我的箭羽快用完了。如果有人能给我弄点就太好了。",
    "I need some equipment to refill my stocks. I don't work with wood, Splinta is busy this week and people still come to my shop to get WOODEN stuff, seriously.": "我需要一些装备来补充库存。我不与木材打交道，斯普林塔 这周很忙，但仍然有人来我的店里买木制的东西，说真的。",
    "Iron Ore": "铁矿石",
    "Job board": "求职板",
    "Job Board": "求职板",
    "Journal entry added (Travelers - Polus)": "增加日志条目（旅行者 - 波洛斯）",
    "Leo's Tannery": "里奥的制革厂",
    "Leo's Tannery Assortment": "里奥的制革厂分类",
    "MAX": "最大",
    "Minor Healing Potion": "小型治疗药水",
    "Misha": "米莎",
    "Misha's Threads": "米莎的丝线",
    "Misha's Threads Assortment": "米莎的丝线分类",
    "MP Regeneration": "法力值恢复",
    "My most recent research into mild poison requires some rat tails. Please deliver with haste.": "我最近对温和毒药的研究需要一些老鼠尾巴。请尽快交货。",
    "Need rat meat. While not very tasty, it's a feast for poor people.": "需要老鼠肉。虽然不是很好吃，但这是穷人的盛宴。",
    "Polus": "波洛斯",
    "Quest": "任务",
    "Quests of this rank are locked.": "这个等级的任务被锁定。",
    "Book": "书",
    "Requirements": "要求",
    "Rewards": "奖励",
    "Silver's Trinkets": "银饰品",
    "Sit by the Bar": "坐在吧台旁",
    "Splinta": "斯普林塔",
    "Splinta's arrow needs": "斯普林塔的箭需要",
    "Splinta's twigs": "斯普林塔的树枝",
    "Splinta's Woodcrafts": "斯普林塔的木制品",
    "Splinta's Woodcrafts' Assortment": "斯普林塔的木制品分类",
    "Time Limit": "时间限制",
    "Training Sword": "训练剑",
    "Twig": "小树枝",
    "We serve only the best food and drinks": "我们只供应最好的食物和饮料",
    "What will it be?": "会是什么呢？",
    "Whether you are looking for a job or a drink, you are at the right place.": "无论你是找工作还是喝酒，你都来对地方了。",
    "Wooden Shield": "木盾",
    "Workshops everywhere you look": "到处都是工坊",
    "Zuris' Scrolls": "祖里斯的卷轴",
    "Zuris' Scrolls Assortment": "祖里斯的卷轴分类",
    "Workshops everywhere you look, but they are all closed for the night": "到处都是作坊，但晚上都关门了",
    "A beautiful young woman stands behind the desk": "一位漂亮的年轻女子站在桌子后面",
    "Complete All": "完成全部",
    "Complete All Quests": "完成所有任务",
    "Reception": "服务台",
    "Which request would you like to turn in?": "您想提交哪项请求？",
    "Will instantly complete all quests that you meet the requirements for.": "会立即完成所有符合要求的任务。",
    "A small cabin can be seen in the distance": "远处可以看到一间小木屋",
    "Forest Clearing": "森林空地",
    "Forest Outskirts": "森林外围",
    "Gather Herbs": "采集药草",
    "Harvest Wood": "采集木材",
    "Hunter's Cabin": "猎人的小屋",
    "Not enough money": "没有足够的钱",
    "But don't go in too deep, some of the creatures in the depths are really dangerous. There have even been sightings of a huge bear...": "但不要深入太深，深处的一些生物真的很危险。甚至有人看到过一只巨大的熊……",
    "Close to the clearing, pretty safe area with some small game.": "靠近空地，很安全，有一些小猎物。",
    "Close to the clearing, safe area to gather some wood.": "靠近空地，在安全的地方收集一些木材。",
    "Hello there, anything you need?": "你好，有什么需要吗？",
    "Hunt": "狩猎",
    "Meat, hides, bones and wood can all be obtained here.": "肉、兽皮、骨头和木头都可以在这里获得。",
    "The walls are decorated by hunting trophies.": "墙上装饰着狩猎战利品。",
    "Tree": "树",
    "Well, you are in a forest, you can get a lot of useful things here.": "嗯，你在森林里，你可以在这里得到很多有用的东西。",
    "Close to the clearing, safe area to gather some very basic herbs... among the thousands of weeds.": "靠近空地，安全的地方收集一些非常基本的草药…在成千上万的杂草中。",
    "A piece of feather.": "一片羽毛。",
    "A piece of wood.": "一块木头。",
    "A twig, quite brittle.": "一根树枝，很脆。",
    "Deadline": "截止日期",
    "Earth Hatred": "土系仇恨",
    "Herb, commonly used in medicine.": "草药，通常用于医学。",
    "I want to make some hats from rabbit furs. Please provide the furs.": "我想用兔毛做几顶帽子。请提供毛皮。",
    "Leather": "皮革",
    "Leo": "利奥",
    "Leo's hats": "利奥的帽子",
    "Plant Hatred": "植物仇恨",
    "Rabbit Fur": "兔毛",
    "Wood": "木材",
    "Herbalism": "草药学",
    "Improves damage against Plant race enemies.": "提高对植物种族敌人的伤害。",
    "Kill 100 enemies.": "杀死 100 个敌人",
    "Kill 100 plant enemies.": "杀死 100 个植物敌人",
    "Skill": "技能",
    "Woodcutting": "伐木",
    "Acquire the enemy card in order to unlock this entry.": "获取敌人的卡牌以解锁此入口。",
    "First of many.": "这是第一个。",
    "Kill 1 enemy.": "击杀 1 敌人.",
    "MAX HP": "生命值上限",
    "Tenacity": "坚韧",
    "Tis but a scratch.": "不过是擦伤而已。",
    "Some random drunk guy in the tavern complaining about how young people these days waste their time, while they should instead climb the tower.": "酒馆里某个喝醉的家伙抱怨现在的年轻人是如何浪费时间的，而他们应该爬上高塔。",
    "Alchemy Prof.": "炼金术教授",
    "Beast Hatred": "野兽仇恨",
    "Beast Resistance": "野兽抵抗",
    "Blacksmithing Prof.": "锻造教授。",
    "Construct Hatred": "结构仇恨",
    "Construct Resistance": "结构抗性",
    "Cooking Prof.": "烹饪教授",
    "Earth Affinity Exp": "土系亲合力经验",
    "Earth Power": "土系之力",
    "Earth Resistance": "土系抗性",
    "Enchanting Prof.": "附魔教授",
    "EXP Rate": "经验速率",
    "Exp Rate": "经验速率",
    "Fire Affinity Exp": "火系亲和经验",
    "Fire Hatred": "火之仇恨",
    "Fire Power": "火之力量",
    "Fire Resistance": "火系抗性",
    "Formless Hatred": "无形的仇恨",
    "Formless Resistance": "无形抵抗",
    "Gluttony Exp": "暴食经验",
    "Herbalism Exp": "草药学经验",
    "Holy Affinity Exp": "神圣系亲和经验",
    "Holy Hatred": "神圣仇恨",
    "Holy Power": "神圣力量",
    "Holy Resistance": "神圣抵抗",
    "HP Regeneration (%)": "生命回复（%）",
    "Humanoid Hatred": "人形仇恨",
    "Humanoid Resistance": "人形抗性",
    "Insect Hatred": "昆虫仇恨",
    "Insect Resistance": "昆虫抵抗",
    "Jewelcrafting Exp": "珠宝加工经验",
    "Jewelcrafting Prof.": "珠宝加工教授。",
    "Leatherworking Exp": "皮革加工经验",
    "Leatherworking Prof.": "皮革加工教授。",
    "Mana Control Exp": "法力控制经验",
    "Mana Efficiency": "魔法效率",
    "Max HP": "最大生命值",
    "Max MP": "最大法力值",
    "Mining Exp": "采矿经验",
    "MP Regeneration (%)": "法力值回复（%）",
    "Mutilation Exp": "切割经验",
    "Neutral Power": "中立之力",
    "Neutral Resistance": "中立抵抗",
    "Plant Resistance": "植物抗",
    "Runecarving Exp": "符文雕刻经验",
    "Runecarving Prof.": "符文雕刻教授",
    "Scrollcrafting Exp": "卷轴制作经验",
    "Scrollcrafting Prof.": "卷轴制作教授",
    "Shadow Affinity Exp": "暗影系亲和经验",
    "Shadow Hatred": "暗影仇恨",
    "Shadow Power": "暗影力量",
    "Shadow Resistance": "暗影抵抗",
    "Studying Exp": "学习经验",
    "Studying Speed": "学习速度",
    "Tailoring Prof.": "裁剪教授",
    "Tenacity Exp": "坚韧经验",
    "Water Hatred": "水之仇恨",
    "Water Power": "水之力量",
    "Water Resistance": "水系抗性",
    "Wind Affinity Exp": "风系亲和经验",
    "Wind Hatred": "风之仇恨",
    "Wind Power": "风之力量",
    "Wind Resistance": "风系抗性",
    "Woodcutting Exp": "伐木经验",
    "Woodworking Exp": "木工经验",
    "Woodworking Prof.": "木工教授",
    "Affects damage dealt by physical attacks.": "影响物理攻击造成的伤害。",
    "Affects damage dealt by spells.": "影响法术造成的伤害。",
    "Base": "基础",
    "Decreases mana required to cast spells (in percentage).": "减少施法所需的法力值（百分比）。",
    "Decreases shop prices (by percentage, capped at 75%).": "降低商店价格（按百分比计算，上限为75%）。",
    "Determines critical chance. 1 point equals 0.1% chance.": "决定致命几率。1分等于0.1%的概率。",
    "Determines damage received from bleeding. Each point equals 1% reduction (up to 100%).": "决定因出血而受到的伤害。每点等于减少1%（最多100%）。",
    "Determines damage received from burning. Each point equals 1% reduction (up to 100%).": "决定燃烧造成的伤害。每点等于减少1%（最多100%）。",
    "Determines damage received from physical attacks. Each point of defense equals 1% damage reduction (up to 95%).": "决定受到物理攻击的伤害。每点防御等于1%的伤害减免（最多95%）。",
    "Determines damage received from poison. Each point equals 1% reduction (up to 100%).": "决定从毒药中受到的伤害。每点等于减少1%（最多100%）。",
    "Determines damage received from spells. Each point of magical defense equals 1% damage reduction (up to 95%).": "决定受到的法术伤害。每点魔法防御等于1%的伤害减免（最多95%）。",
    "Determines the amount of mana you recover (in percentage of your maximum mana) each tick. Works in combat.": "决定你每一秒恢复的法力值（占你最大法力值的百分比）。在战斗中起作用。",
    "Determines the amount of mana you recover each tick. Works in combat.": "决定你每次回复的法力值。在战斗中起作用。",
    "Determines the amount you get healed (in percentage of your maximum health) each tick. Works in combat.": "决定你每次被治疗的数量（以你最大生命值的百分比计算）。在战斗中起作用。",
    "Determines the amount you get healed each tick. Works in combat.": "决定你每次被治愈的数量。在战斗中起作用。",
    "Determines your magical ability. Is consumed on spell usage.": "决定了你的魔法能力。在使用法术时消耗。",
    "Determines your survivability. You get knocked out when this reached 0.": "决定你的生存能力。当这个等于0时，你就被淘汰了。",
    "Final damage reduction, applied at the very end for both physical attacks and spells damage calculation.": "最终伤害减少，应用于最后的物理攻击和法术伤害计算。",
    "First Blood": "第一滴血",
    "Increases damage dealt by critical hits. Default damage of critical hits is 200%. This value further increases it by 1% per 1 point.": "增加暴击造成的伤害。爆击的默认伤害是200%。此值每1点进一步增加1%。",
    "Increases drop rate. One point equals 1% increase. Effect is applied on bestiary entries.": "增加掉落率。1分等于1%的增长。效果适用于动物条目。",
    "Increases the efficiency of reading (by percentage).": "提高阅读效率（按百分比）。",
    "Increases the experience you gain (only level experience, not skills and equipment). One point equals 1% increase.": "增加你获得的经验值（只增加等级经验值，不增加技能和装备）。1分等于1%的增长。",
    "Level": "等级",
    "Ouch!": "哎哟！",
    "Sources": "来源",
    "Tenacity": "坚韧",
    "Alchemy": "炼金术",
    "Blacksmithing": "锻造",
    "Chronomancy": "计时",
    "Combat Mastery": "战斗精通",
    "Cooking": "烹饪",
    "Earth Affinity": "土系亲合力",
    "Enchanting": "附魔",
    "Fire Affinity": "火系亲和力",
    "Gluttony": "暴食",
    "Herbalism": "草药学",
    "Holy Affinity": "神圣系亲和力",
    "Jewelcrafting": "珠宝加工",
    "Leatherworking": "皮革加工",
    "Mana Control": "法力控制",
    "Mining": "采矿",
    "Mutilation": "切割",
    "Runecarving": "符文雕刻",
    "Scrollcrafting": "卷轴制作",
    "Shadow Affinity": "暗影亲和力",
    "Studying": "学习",
    "Tailoring": "裁剪",
    "Tenacity": "坚韧",
    "Trading": "交易",
    "Water Affinity": "水系亲和力",
    "Wind Affinity": "风系亲和力",
    "Woodcutting": "伐木",
    "Woodworking": "木工",
    "Decreases the amount of materials required when crafting. Each point equals 1% decrease (minium of 1 material always required).": "减少制作时所需材料的数量。每个点等于减少1%（总是需要最少1种材料）。",
    "Earth Hatred I": "土系仇恨 I",
    "Earth Hatred": "土系仇恨",
    "Herbalism": "草药学",
    "Neutral Hatred": "中立仇恨",
    "Plant Hatred I": "植物仇恨 I",
    "Plant Hatred": "植物仇恨",
    "Woodcutting": "伐木",
    "Afflicted Silence Time": "折磨沉默时间",
    "Afflicted Stun Time": "折磨眩晕时间",
    "Beast Killed": "击杀野兽",
    "Burning Damage Received": "受到的火系伤害",
    "Earth Damage Dealt": "造成的土系伤害",
    "Earth Damage Received": "受到的土系伤害",
    "Earth Killed": "击杀土系",
    "Enchants Applied": "应用的附魔",
    "Enchants Overwritten": "附魔被覆盖",
    "Fire Damage Dealt": "造成的火系伤害",
    "Fire Damage Received": "受到的火系伤害",
    "Fire Killed": "击杀火系",
    "Food Consumed": "消耗的食物",
    "Health Potions Consumed": "消耗的生命药水",
    "Holy Damage Dealt": "造成的神圣伤害",
    "Holy Damage Received": "受到的神圣伤害",
    "Holy Killed": "击杀神圣",
    "Humanoid Killed": "击杀人形",
    "Insect Killed": "击杀昆虫",
    "Items Bought": "购买的物品",
    "Items Crafted": "制作的物品",
    "Items Obtained": "获得的物品",
    "Magical Damage Dealt": "造成的魔法伤害",
    "Magical Damage Received": "受到的魔法伤害",
    "Mana Potions Consumed": "法力药水消耗",
    "Money Gained": "赚到的钱",
    "Money Spent": "花掉的钱",
    "Neutral Damage Dealt": "造成的中立伤害",
    "Neutral Damage Received": "受到的中立伤害",
    "Physical Damage Dealt": "造成的物理伤害",
    "Physical Damage Received": "受到的物理伤害",
    "Plant Killed": "击杀植物",
    "Poison Damage Dealt": "造成的中毒伤害",
    "Poison Damage Received": "受到的中毒伤害",
    "Quests Finished": "完成任务",
    "Races Killed": "击杀种族",
    "Readables Read": "阅读的可读内容",
    "Rebirth Count": "重生次数",
    "Scenes Entered": "进入的场景",
    "Shadow Damage Dealt": "造成的暗影伤害",
    "Shadow Damage Received": "受到暗影伤害",
    "Shadow Killed": "击杀暗影",
    "Status Effects Applied": "应用的状态效果",
    "Status Effects Received": "受到的状态效果",
    "Time Slept": "睡眠时间",
    "Time Spent Silenced": "沉默时长",
    "Time Spent Stunned": "眩晕时间",
    "Total Skill Level Ups": "总技能等级提升",
    "Water Damage Dealt": "造成的水系伤害",
    "Water Damage Received": "受到的水系伤害",
    "Wind Damage Dealt": "造成的风系伤害",
    "Wind Damage Received": "受到风系伤害",
    "Wind Killed": "击杀风系",
    "HP": "生命值",
    "Health Potion": "消耗品 / 生命药水",
    "Cheap version of the healing potion, has minor healing effect.": "廉价版本的治疗药水，有轻微的治疗效果。",
    "Finish a quest.": "完成一个任务。",
    "Laborer": "劳动者",
    "Reset game": "重置游戏",
    "This cannot be undone.": "这是不可撤销的。",
    "This will completely reset the game. Everything will be removed, including permanent progression.": "这将完全重置游戏。所有东西都将被移除，包括永久进度。",
    "Chef's raw meat": "厨师的生肉",
    "Raw Meat": "生肉",
    "Splinta's wood supply": "斯普林塔的木材供应",
    "I need some proper meat to feed all of you": "我需要一些合适的肉来喂饱你们",
    "I would appreciate if someone could bring me some wood. Less time spent in forest means more time making life-saving equipment. Thank you": "如果有人能给我拿些木头来，我会很感激的。在森林里待的时间越少，制造救生设备的时间就越多。谢谢你！",
    "Hoarder": "囤积者",
    "A piece of rabbit fur.": "一块兔毛。",
    "A piece of raw flesh, better cook it first.": "一块生肉，最好先煮熟。",
    "Meat Shield": "肉盾",
    "Your ability to fight, mainly improves the power of your strikes.": "你的战斗能力，主要是提高你打击的力量。",
    "Still full of rats": "仍然满是老鼠",
    "You've had enough for now": "现在你已经有足够的了",
    "A room much bigger than the outside would suggest. A huge runestone stands in the middle.": "一个比外面看起来大得多的房间。中间矗立着一块巨大的符文石。",
    "Copy down the unfamiliar runes": "把不熟悉的符文抄下来",
    "Crafted at the Scrollcrafting and Runecarving stations.": "在卷轴制作和符文雕刻站制作。",
    "Scroll Of Arcane Bolt": "奥术弩箭卷轴",
    "Arcane Bolt": "奥术弩箭",
    "Each floor, a Guardian oversees.": "每层都有一名守护者负责监督。",
    "first runestone": "第一块符文石",
    "Hallway": "走廊",
    "Mana Fragment": "法力碎片",
    "Materials": "材料",
    "Read the runestone": "阅读符文石",
    "Diagram": "图表",
    "Runestone filled with runes, some you instinctively understand, others you cannot comprehend.": "满是符文的符文石，有些你本能地能理解，有些你不能理解。",
    "Teaches how to make Scroll Of Arcane Bolt.": "用于教授如何制作奥术弩箭之卷。",
    "The first rune of passage and the first secret of magic are a gift of the Tower to anyone brave enough to enter.": "第一个通道符文和第一个魔法秘密是送给任何勇敢进入塔内的人的礼物。",
    "Those worthy enough shall be conveyed a rune of passage and a secret of magic.": "那些足够有价值的人将会得到一个通道符文和一个魔法秘密。",
    "Currently reading": "当前正在阅读",
    "You can continue where you left off.": "你可以从你停下的地方继续。",
    "Stop Reading": "停止阅读",
    "Stop reading": "停止阅读",
    "Bookworm": "书呆子",
    "Read a book.": "读一本书。",
    "Quest expired. Lost 5 reputation.": "任务已过期。失去 5 声誉。",
    "Studying speed": "学习速度",
    "You've already done that.": "你已经做过了。",
    "Arcane Bolt.": "奥术弩箭。",
    "A dark, dungeon-like space. Some strange creatures can be seen roaming around.": "一个黑暗、地牢般的空间。可以看到一些奇怪的生物在周围游荡。",
    "An arrow made of fire.": "用火制成的箭。",
    "as magical damage": "火焰伤害",
    "Deals 200% of": "造成 200% 的",
    "Explore deeper": "深入探索",
    "Fire Arrow": "火焰箭",
    "Water Slime": "水系史莱姆",
    "Fire Slime": "火系史莱姆",
    "Fire Slime used <Fire Arrow": "火系史莱姆 使用了 <火焰箭",
    "Water Slime used <Water Splash": "水系史莱姆 使用了 <水花飞溅",
    "MP": "法力值",
    "Spell": "法术",
    "Water Splash": "水花飞溅",
    "Dangerous beasts lurk around.": "危险的野兽潜伏在周围。",
    "Forest Depths": "森林深处",
    "Go deeper": "更深入",
    "Having hunted for a while, you consider going deeper into the woods.": "在狩猎了一段时间后，你考虑深入森林。",
    "Return to City": "返回城市",
    "Hunt indefinitely": "无限狩猎",
    "Thank you": "谢谢你",
    "Stone Bullet": "石弹",
    "Scroll": "卷轴",
    "Rune": "符文",
    "Wind Blast": "风爆",
    "Alchemy manual": "炼金术手册",
    "Alchemy Theory": "炼金术理论",
    "Accessories Assortment": "饰品分类",
    "Bone": "骨头",
    "Bone Dust": "骨粉",
    "Bone Dust.": "骨粉.",
    "Leather Armor.": "皮甲.",
    "Leather Shoes.": "皮鞋.",
    "Leather Hat.": "皮帽.",
    "Leather.": "皮革.",
    "Iron Ring.": "铁戒指.",
    "Boar Tusk": "野猪牙",
    "Bat Wing": "蝙蝠翅膀",
    "Ask about ore": "询问关于矿石的事情",
    "Ask about free equipment": "询问关于免费装备的事情",
    "Ask about the whereabouts": "询问在什么地方",
    "Anything you fancy?": "你喜欢什么？",
    "Minor Damage Reduction": "轻微伤害减免",
    "Minor Dexterity": "轻微灵巧",
    "Minor Intelligence": "轻微智力",
    "Minor Magical Defense": "轻微魔法防御",
    "Minor Strength": "轻微力量",
    "Minor Dr": "轻微伤害减免",
    "Minor Experience": "轻微经验值",
    "Minor Health": "轻微生命值",
    "Minor Mdef": "轻微魔法防御",
    "Minor Damage Reduction.": "轻微伤害减免.",
    "Minor Dexterity.": "轻微灵巧.",
    "Minor Intelligence.": "轻微智力.",
    "Minor Magical Defense.": "轻微魔法防御.",
    "Minor Strength.": "轻微力量.",
    "Minor Dr.": "轻微伤害减免.",
    "Minor Experience.": "轻微经验值.",
    "Minor Health.": "轻微生命值.",
    "Minor Mdef.": "轻微魔法防御.",
    "Headgear": "头饰",
    "Armor": "护甲",
    "Shoes": "鞋子",
    "Weapon": "武器",
    "Goat Horn": "山羊角",
    "Goat Horns": "山羊角",
    "Godspeed, kid.": "祝你好运，孩子。",
    "Healing Potion": "治疗药水",
    "Enchanted Water.": "附魔之水。",
    "Wolf Fang": "狼牙",
    "Wolf Fang Amulet": "狼牙护身符",
    "Enchants Assortment": "附魔分类",
    "Mana Potion": "法力药水",
    "Pickaxe": "镐子",
    "Now get out.": "现在滚出去。",
    "Slime": "史莱姆",
    "experience gained": "经验值增益",
    "Hmm?": "嗯?",
    "But no, the guys I have do a great job and keep me well supplied. And when that is not enough, I just post a job with the Guild and they sort it out, so I don't have a need for anyone else.": "但是没有，我的队友们做得很好，给了我充足的补给。当这还不够的时候，我就在公会发布一份工作，他们会把它整理出来，所以我不需要其他人。",
    "A hat made out of regular leather, provides minor protection.": "一顶由普通皮革制成的帽子，只提供轻微的保护。",
    "A hint of compassion can be seen in her eyes.": "从她的眼睛里可以看出一丝同情。",
    "A pair of shoes made out of regular leather, provides decent protection.": "一双由普通皮革制成的鞋子，提供了不错的保护。",
    "A piece of blank runestone, very rare and valuable. Used in making spell runes.": "一块空白的符文石，非常稀有和珍贵。用于制作符文。",
    "Also, since you made me laugh, here's a felling axe to help you out.": "还有，既然你把我逗笑了，这把砍柴斧头可以帮你一把。",
    "An armor made out of regular leather, provides decent protection while being very flexible.": "一种由普通皮革制成的盔甲，提供了良好的保护，同时非常灵活。",
    "An illusion of golden sheen can be seen in her eyes.": "从她的眼睛里可以看出一种金色光泽的幻觉。",
    "An old man is seen tinkering with flasks.": "一个老人在摆弄烧瓶。",
    "Barely pays you any attention": "几乎没有注意到你",
    "Beautiful young lady is busy tinkering with delicate tools.": "漂亮的年轻女士正忙着摆弄精致的工具。",
    "Blast of wind, not very powerful.": "一阵风，不是很猛烈。",
    "Burly man stands behind the counter.": "一个魁梧的男人站在柜台后面。",
    "Can I become one of your suppliers?": "我可以成为你们的供应商之一吗？",
    "Cheap version of the mana potion, restores a small amount of mana.": "廉价版的法力药水，恢复少量法力。",
    "Come back when you have the wood. Remember, you need the tools here.": "等你有了木头再来。记住，你需要这些工具。",
    "Condensed magic power in the form of damaging bolt.": "凝聚的魔法力量，以破坏闪电的形式出现。",
    "Craft": "制造",
    "Crafted at the Alchemy station.": "在炼金术站制作。",
    "Crafted at the Enchanting station.": "在附魔站制作。",
    "Crafted at the Jewelcrafting station.": "在珠宝加工站制作。",
    "Crafted at the Leatherworking station.": "在皮革加工站制作。",
    "Crakon's Potions Assortment": "克拉肯药剂店",
    "Crystallized mana, rarely found in entities of magical nature, or those touched by mana.": "水晶魔法，很少在魔法实体中发现，或者那些被魔法接触过的实体。",
    "Doubles the amount of ore gained from veins.": "从矿脉中获得的矿石量翻倍。",
    "Empty enchant slot": "空附魔槽",
    "Enchanting manual": "附魔手册",
    "Enchanting Theory": "附魔理论",
    "Enchants Assortment": "附魔分类",
    "Full of stands outfitted with leather armor.": "到处都是装备着皮甲的架子。",
    "Good luck on your journey and stay safe. There is no shame in retreat, you can always try again as long as you survive.": "祝你旅途好运，注意安全。退却并不可耻，只要你活下来，你就可以再试一次。",
    "Hah, you are a funny one, are you not?": "哈，你是个有趣的人，不是吗？",
    "Hahaha, you are bold": "哈哈哈，你真大胆",
    "Her kind look leaves no pressure on you.": "她和蔼的样子不会给你带来压力。",
    "However, boldness should be rewarded, so I will take you up for a single job, since I was just about to head to the Guild to post a contract.": "然而，勇敢应该得到奖励，所以我将带你去做一件事，因为我正准备去公会发布一份合同。",
    "However, here are diagrams for a training sword and a wooden shield.": "不过，这里有训练剑和木盾的示意图。",
    "I also have some dedicated suppliers, who delve into an abandoned mining shaft in the forest.": "我也有一些专门的供应商，他们深入研究了森林里的一个废弃矿井。",
    "I hope you are here to buy and not just to look.": "我希望你是来买东西的，而不是来看看的。",
    "I will give you a free Pickaxe to make your life a bit easier, and if you manage to bring me 50 iron ores, I will even teach you how to make it.": "我会免费送你一把鹤嘴锄，让你的生活轻松一点，如果你能给我带来50块铁矿石，我甚至会教你怎么做。",
    "If there is someone to give out free help to others, it is her.": "如果有人免费帮助别人，那一定是她。",
    "If you need some ore yourself, you can buy it from me without the risk of losing a limb or two. The price is, obviously, fair.": "如果你自己也需要一些，你可以从我这里买，而不会有失去四肢的风险。这个价格显然是公平的。",
    "In the woods obviously, silly": "显然是在树林里，傻瓜",
    "Iron Earring": "铁耳环",
    "Iron Ingot": "铁锭",
    "Iron Ring": "铁戒指",
    "Items with strange aura are in the shelves.": "货架上摆放着带有奇怪光环的物品。",
    "Its not really a secret, since not many people can manage that place. It is infested with some pretty dangerous creatures.": "这并不是什么秘密，因为没有多少人能管理好那个地方。那里有很多非常危险的生物。",
    "Jewelcrafting manual": "珠宝加工手册",
    "Jewelcrafting Theory": "珠宝加工理论",
    "Just go in, stay away from the wildlife and cut down some trees.": "只要进去，远离野生动物，砍几棵树。",
    "Kind-looking woman walks around the shop.": "一位和蔼的女士在商店里走来走去。",
    "Leather Armor": "皮甲",
    "Leather Hat": "皮帽",
    "Leather Shoes": "皮鞋",
    "Leatherworking manual": "皮革加工手册",
    "Leatherworking Theory": "皮革加工理论",
    "Middle-aged man with an arrogant look stand near the shelves containing precious scrolls.": "一脸傲慢的中年男子站在摆满珍贵书卷的书架旁。",
    "Minor Mana Potion": "轻微魔法药水",
    "Most people find some while climbing the tower. Having no use for it they will happily fulfill my commissions despite the somewhat... profitable rates.": "大多数人在爬塔的时候都会找到一些。他们不需要它，他们会很高兴地完成我的任务，尽管有点……有利可图的利率。",
    "No freebies here, kid. Go try Splinta's woodworking shop across the streets.": "这里没有免费赠品，孩子。去街对面斯普林塔的木工店试试。",
    "No worries, while most don't remember, or are too prideful to, we all started where you are right now.": "别担心，虽然大多数人不记得了，或者太骄傲了，但我们都是从你现在的位置开始的。",
    "No, I will not give you any equipment for free.": "不，我不会免费送你任何装备的。",
    "Now go, no time to idle": "现在走吧，没时间闲着",
    "Of course we have some equipment available": "当然我们有一些可用的装备",
    "Or you can buy some from me, but we probably wouldn't be having this conversation if you had the money to do that, right?": "或者你可以从我这里买一些，但如果你有钱的话，我们可能就不会有这个谈话了，对吧？",
    "Pickaxe used for mining ores.": "挖矿用的镐。",
    "Processed material, mostly used in making leather armor and durable working clothes.": "加工过的材料，主要用于制作皮革盔甲和耐用的工作服。",
    "Raw Hide": "生皮",
    "Raw material used in crafting leather.": "用于制作皮革的原料。",
    "Scrollcrafting manual": "卷轴制作手册",
    "Scrollcrafting Theory": "卷轴制作理论",
    "She can barely hold in her laugh.": "她几乎忍不住笑了。",
    "Small and filled with impurities.": "小而充满杂质。",
    "Small rock flying at the speed of wind.": "以风速飞行的小岩石。",
    "Small-sized spray of water.": "小小的水花。",
    "Splinta's Woodcrafts' Assortment": "斯普林塔的木制品分类",
    "Standard healing potion, has decent healing effect": "标准治疗药水，有不错的治疗效果",
    "Standard mana potion, restores a decent amount of mana.": "标准的法力药水，恢复相当数量的法力。",
    "Suspects you of not having money to afford these.": "我怀疑你没钱买这些东西。",
    "Tailoring Station": "裁剪站",
    "Antidote.": "解药。",
    "Enchanted Water.": "迷人的水。",
    "Healing Potion.": "治疗药水。",
    "Iron Earring.": "铁耳环。",
    "Mana Potion.": "法力药水。",
    "Minor Healing Potion.": "小型治疗药水。",
    "Minor Mana Potion.": "小型魔法药水。",
    "Wolf Fang Amulet.": "狼牙护身符。",
    "To make them, you will need to gather some wood and have appropriate crafting station, you can use mine in the shop, free of charge.": "为了制作它们，你需要收集一些木材和合适的工艺站，你可以在商店里免费使用我的。",
    "Try to kill all the rats": "尝试把老鼠都杀了",
    "Um... where do I get wood?": "嗯…我从哪里得到木头？",
    "Well, I commission it from others via the Adventurers' Guild.": "嗯，我是通过冒险家协会委托别人做的。",
    "What? For free? Are you out of your mind?": "怎么啦？免费吗?你疯了吗？",
    "Where do I get my ore?": "我从哪里得到我的矿石？",
    "Woodworking Station": "木工站",
    "Axe used for cutting trees.": "用来砍树的斧头。",
    "Crafted at the Woodworking station.": "在木工站制作。",
    "Doubles the amount of wood gained from trees.": "从树木中获得的木材量翻倍。",
    "Felling Axe": "伐木斧",
    "Training Sword.": "训练剑。",
    "Wooden Armguard": "木制护手",
    "Wooden Armguard.": "木制护手。",
    "Wooden Shield.": "木制盾牌。",
    "Woodcutting Experience": "伐木经验",
    "Warthog": "疣猪",
    "Cannot do that while doing another action (reading, fighting, crafting, shopping,...).": "不能在执行其他操作（阅读、战斗、制作、购物等）时这样做。",
    "Improves your ability to learn new things.": "提高你学习新事物的能力。",
    "Item rank up": "物品品阶提升",
    "Wind Slime": "风史莱姆",
    "Mana Sting": "法力之刺",
    "Mountain Goat": "山羊",
    "Mountain Goat used <Impale": "山羊 使用了 <刺穿",
    "Wolf": "狼",
    "Causes": "原因",
    "A venomous bite.": "剧毒的咬伤。",
    "Bone extracted from medium-sized beast. Can be processed in multiple ways.": "从中型野兽身上提取的骨头。可以以多种方式处理。",
    "Just 5 more minutes...": "再给我5分钟…",
    "Stay in bed for a total of 10 hours (cumulative, real time).": "累计在床上待10个小时（累计，现实时间）。",
    "Earth Fragment": "土系碎片",
    "Earth Fragments": "土系碎片",
    "Fire Fragment": "火焰碎片",
    "Fire Fragments": "火焰碎片",
    "Shadow Fragment": "暗影碎片",
    "Shadow Fragments": "暗影碎片",
    "Wind Fragment": "风之碎片",
    "Wind Fragments": "风之碎片",
    "Get me some ores so I can resell them for profit": "给我弄点矿石来，我可以转卖赚钱",
    "I have been looking for a nice pelt that I could make into a cloak for a while.": "我一直在寻找一种可以做成斗篷的好毛皮。",
    "Mana Fragments": "法力碎片",
    "Ore": "矿石",
    "Pristine bear pelt": "原始熊皮",
    "Pristine Bear Pelt": "原始熊皮",
    "Water Fragment": "水之碎片",
    "Water Fragments": "水之碎片",
    "Zuris": "祖里斯",
    "Wool": "羊毛",
    "Misha's wool": "米莎的羊毛",
    "I need some goat horns. I can make an enchantment to improve magical defense out of them.": "我需要一些羊角。我可以用魔法来提高他们的魔法防御能力。",
    "I am running low on wool and my usual supplier is nowhere to be seen.": "我的羊毛快用完了，而我的老供应商也不见了踪影。",
    "/ Card": "/ 卡片",
    "It's magic": "这是魔法",
    "Wind Sting": "风刺",
    "Water Sting": "水刺",
    "Fire Sting": "火刺",
    "Earth Sting": "土刺",
    "Fang Amulet": "牙齿护身符",
    "Bear Cloak": "熊斗篷",
    "Open the door": "打开门",
    "Talk to Kathryn": "与凯思琳交谈",
    "(Check question mark in inventory to learn about feeding)": "（检查库存中的问号以了解喂养情况）",
    "A familiar figure stands by the gate.": "一个熟悉的身影站在门口。",
    "grows hungry...": "肚子饿了……",
    "Hunting Bow": "狩猎弓",
    "Iron Armor": "铁盔甲",
    "Iron Boots": "铁靴子",
    "Iron Helmet": "铁头盔",
    "Proficient": "精通",
    "The now familiar gate stands before you.": "那扇熟悉的大门就在你面前。",
    "Bear": "熊",
    "MAX MP": "法力值上限",
    "Offhand": "副手",
    "A cloak made out of pristine bear pelt. Surprisingly very sturdy, provides moderate protection.": "用原始熊皮制成的斗篷。令人惊讶的是非常坚固，提供适度的保护。",
    "A few pieces of wood strung together, provides some protection.": "几块木头串在一起，可以提供一些保护。",
    "A pair of boots made out of iron, provides very good protection when it comes to mundane equipment.": "一双铁制的靴子，在日常装备方面提供了很好的保护。",
    "All Skills Experience": "所有技能经验",
    "Amulet": "护身符",
    "An amulet made out of wolf fangs. A hunter's trophy.": "用狼牙做的护身符。猎人的战利品。",
    "An armor made out of iron, provides very good protection when it comes to mundane equipment.": "一种由铁制成的盔甲，在日常装备中提供非常好的防护。",
    "Basic helmet made out of iron, provides very good protection when it comes to mundane equipment.": "基本的头盔是由铁制成的，在日常装备方面提供了很好的保护。",
    "Cast your very first spell.": "释放你的第一个法术",
    "Garment": "服装",
    "Handy shield, might save your life.": "方便的盾牌，也许能救你一命。",
    "Improves your ability to haggle for a better price.": "提高你讨价还价的能力。",
    "Right Accessory": "右侧配饰",
    "The ability to deal fatal damage.": "造成致命伤害的能力。",
    "Use mana for the first time.": "第一次使用法力。",
    "Useful for hunting game": "对狩猎很有用",
    "Using mana increases your proficiency with it, decreasing the amount required by spells.": "使用法力可以提高你的熟练度，减少法术所需的法力量。",
    "A large, circular room lit by standing candelabras.": "大的圆形房间，由站立的大烛台照亮",
    "Another victory, another rune on your arm, this time for the fourth floor.": "又一次胜利，手臂上的另一个符文，这次是第四层。",
    "Challenge the Guardian": "挑战守护者",
    "Crystallized wind-attuned mana, rarely found in entities of wind nature.": "结晶风调法力，很少在风系的实体中发现。",
    "Crystallized water-attuned mana, rarely found in entities of water nature.": "结晶风调法力，很少在水系的实体中发现。",
    "Crystallized fire-attuned mana, rarely found in entities of fire nature.": "结晶火调法力，很少在火系的实体中发现。",
    "Crystallized earth-attuned mana, rarely found in entities of earth nature.": "结晶土调法力，很少在土系的实体中发现。",
    "Crystallized shadow-attuned mana, rarely found in entities of shadow nature.": "结晶暗影调法力，很少在暗影系的实体中发现。",
    "Crystallized holy-attuned mana, rarely found in entities of holy nature.": "结晶神圣调法力，很少在神圣系的实体中发现。",
    "Go back to the Hallway": "回到走廊",
    "Large wolf fang.": "狼的大獠牙。",
    "Mixa, the Rotator": "米沙，旋转者",
    "Novice Tome Page": "新手秘籍页",
    "Perfectly extracted bear pelt, would make for a great cloak. Perhaps someone skilled with leather could help with that.": "完美提取的熊皮，可以用来做一件很棒的斗篷。也许皮革专家能帮上忙。",
    "Random page from Novice Tome, can be reassembled with enough pieces and a diagram.": "新手秘籍中的随机一页，足够的碎片和图表可以重新组装。",
    "Raw material used in crafting cloth.": "用于制作布料的原料。",
    "Raw material used in crafting iron ingots.": "用于制作铁锭的原料。",
    "Said to have mild healing effects. Also used as a binding agent.": "据说有轻微的治疗效果。也用作粘合剂。",
    "The floor Guardian lays defeated.": "守护者被击败了。",
    "Adds a 5% base chance to receive": "增加5%的基础几率收到",
    "Contains the essence of Slime.": "蕴含着史莱姆精华。",
    "Contains the essence of Water Slime.": "蕴含着水系史莱姆精华。",
    "Contains the essence of Mountain Goat.": "蕴含着山羊精华。",
    "Contains the essence of Rat.": "蕴含着老鼠精华。",
    "Contains the essence of Bear.": "蕴含着熊精华。",
    "Contains the essence of Weed.": "蕴含着杂草精华。",
    "Contains the essence of Iron Vein.": "蕴含着铁矿脉精华。",
    "Contains the essence of Wolf.": "蕴含着狼精华。",
    "Contains the essence of Wind Slime.": "蕴含着风系史莱姆精华。",
    "on any kill (non-stacking).": "任意击杀（非叠加）。",
    "Scroll Of Stone Bullet": "石弹卷轴",
    "Scroll Of Stone Bullet.": "石弹卷轴。",
    "Take your reward.": "拿好你的奖励。",
    "Third of many.": "三分之一。",
    "Fight indiscriminately": "不分青红皂白地战斗",
    "Earth Slime": "土系史莱姆",
    "Holy Slimer": "神圣系史莱姆",
    "Holy Fragment": "神圣碎片",
    "Shadow Slimer": "暗影系史莱姆",
    "Shadow Fragment": "暗影碎片",
    " used <Fire Arrow": " 使用了 <火焰箭",
    "Earth Slime used <Stone Bullet": "土系史莱姆 使用了 <石弹",
    "Holy Slimer used <Holy Bolt": "神圣系史莱姆 使用了 <神圣之箭",
    "Shadow Slimer used <Shadow Bolt": "暗影系史莱姆 使用了 <暗影之箭",
    "Holy Bolt": "神圣之箭",
    "Shadow Bolt": "暗影之箭",
    "Bolt made out of dark matter.": "由暗物质制造的箭。",
    "Bolt made out of holy energy.": "由神圣能量制造的箭。",
    "Blacksmithing Proficiency + 1% per level": "锻造熟练度每级增加1%",
    "Cooking Proficiency + 1% per level": "烹饪熟练度每级增加1%",
    "Improves damage against Formless race enemies.": "提高对无形种族敌人的伤害。",
    "Improves your crafting proficiency, resulting in lower material costs.": "提高你的制造熟练度，降低材料消耗。",
    "Jewelcrafting Proficiency + 1% per level": "珠宝加工熟练度每级+ 1%",
    "Leatherworking Proficiency + 1% per level": "皮革加工熟练度每级增加1%",
    "Nothing edible will escape. All shall be consumed.": "任何可吃的东西都逃不掉。一切都将被消灭。",
    "Woodworking Proficiency + 1% per level": "木工熟练度每级增加1%",
    "Bear used <Maul": "熊 使用了 <锤击",
    "Spider used <Poison Bite": "蜘蛛 使用了 <毒咬",
    "Abandoned Mine": "废弃矿井",
    "Maul": "锤击",
    "Cave": "洞穴",
    "Bat": "蝙蝠",
    "Spider": "蜘蛛",
    "Run away": "逃跑",
    "Talk to Jake": "和杰克交谈",
    "Talk to the man": "和那个男人交谈",
    "Iron Vein": "铁矿脉",
    "Mana Usage": "法力消耗",
    "Spellcaster": "施法者",
    "Ore veins are visible in the dim light.": "在昏暗的光线下可以看到矿脉。",
    "From what we know, it appears every 5th floor from the floor of first appearance. It also does not appear on floor lower than the first encounter. This makes it so the earlier you meet it, the more chances to get blessings you get.": "据我们所知，它从第一次出现的楼层开始每隔五层出现一次。它也不会出现在比第一次相遇更低的楼层。因此，你遇见它越早，你得到祝福的机会就越多。",
    "While it is 'like moving to a parallel world', we actually have no idea what is happening, probably some kind of magic. That is because it seems like we travelers exist in all the 'parallel worlds' at the same time.": "虽然这“就像进入了一个平行世界”，但我们实际上不知道发生了什么，可能是某种魔法。这是因为我们这些旅行者似乎同时存在于所有的“平行世界”中。",
    "It is difficult to explain so let me give you an example. If we agree to meet tomorrow and you 'rebirth' today, we will still be in the same world tomorrow and we will be able to meet, despite you accepting a blessing.": "这很难解释，所以我给你举个例子。如果我们同意明天见面，而你今天“重生”，那么明天我们仍然在同一个世界，我们将能够见面，尽管你接受了祝福。",
    "And lastly... we have no idea whether a body is created for us, or whether we take over the one of ourselves within this 'parallel world'. We also don't really like to bring it up, it is the way it is and we can't do much about it.": "最后……我们不知道一个身体是为我们创造的，还是我们在这个“平行世界”中接管了我们自己。我们也不喜欢提起它，事情就是这样，我们对此无能为力。",
    "As we found out, you don't really go back in time. We don't understand the details, but it is more like moving to a parallel world, to that certain time. Which is also why we travelers remember each other after accepting blessings.": "正如我们所发现的，你不可能真正回到过去。我们不了解细节，但它更像是移动到一个平行的世界，到那个特定的时间。这也是为什么我们旅行者在接受祝福后会记住彼此。",
    "Jake": "杰克",
    "The blessings and their power vary depending on the floor and person. One notable blessing is the Heirloom Blessing. It's a blessing that allows you to carry multiple equipment pieces of your choice through the 'rebirth' process. The amount you can take depends on the floor you are at and the power of the equipment.": "祝福和他们的力量因楼层和人而异。一个值得注意的祝福是传家宝祝福。这是一种祝福，允许你在“重生”过程中携带多种你选择的装备。你能取的数量取决于你所在的楼层和装备的功率。",
    "People who have accepted a blessing are called travelers. Some normal people are aware we exist, some not. We usually don't bother explaining things to them, because they won't remember it after we accept another blessing. But it is not a secret.": "接受祝福的人被称为旅行者。有些正常人知道我们的存在，有些则不知道。我们通常懒得向他们解释，因为他们在我们接受了另一个祝福后就不会记得了。但这不是秘密。",
    "This is very useful as it seems that equipment grows more powerful the more you use it. Making it an Heirloom makes this progress permanent. This blessing is the one constant thing in the tower. It is always available, but is limited in its power. An Heirloom Blessing from the 10th floor will not be applicable to a weapon crafted from materials from the 11th floor, for example.": "这是非常有用的，因为似乎装备变得更强大，你使用它越多。使它成为传家宝使这一进程永久。这个祝福是塔里唯一不变的东西。它总是可用的，但它的力量有限。例如，10楼的传家宝祝福将不适用于11楼材料制作的武器。",
    "When you defeat the Shadow, the Tower grants you a blessing. We have no idea how it works, but after accepting it, you go 'back' in time, retaining all your memories and previous blessings.": "当你击败了暗影，高塔就会赐予你祝福。我们不知道它是如何运作的，但在接受它之后，你回到了过去，保留了你所有的记忆和以前的祝福。",
    "A few bones lay here and there.": "到处躺着几根骨头。",
    "A huge bear is in the middle of the cave.": "一只巨大的熊在洞穴中央。",
    "A man stands not far inside the mine.": "一个男人站在矿井里不远处。",
    "Abandoned Mine": "废弃矿井",
    "Also, Shadow may take on different forms depending on the floor you fight it, it also grows stronger the higher you go.": "此外，暗影可能会采取不同的形式，这取决于你打它的楼层，它也会变得更强，你走得越高。",
    "Blessings": "祝福",
    "Enter Forest Depths": "进入森林深处",
    "Fight the bear": "与熊战斗",
    "How the potential is calculated, we have no idea. Some great warriors have never met the Shadow while others, not so prominent, met the Shadow relatively early.": "我们不知道潜力是如何计算的。一些伟大的战士从来没有遇到过暗影，而另一些不那么突出的战士，相对较早地遇到了暗影。",
    "Infested with dangerous critters.": "到处都是危险的生物。",
    "It takes on multiple forms and it seems to be some kind of examiner. Beating it grants you a blessing.": "它有多种形式，看起来像是某种考官。打败它会给你带来祝福。",
    "Kacadu's Shadow, the Examiner. Or as we simply call it, the 'Shadow'": "卡卡杜的影子，考官。或者我们简单地称之为“暗影”",
    "Nice to see you again! Here for more ore?": "很高兴再次见到你！想了解更多吗？",
    "No sign of the generous man...": "没有那个慷慨的人的踪迹……",
    "That's pretty much it about the blessings. The Tower does a pretty good job explaining each blessing when you choose them.": "这就是上帝的祝福。当你选择祝福时，伦敦塔会很好地解释每一种祝福。",
    "The fight with Shadow is also harder and more complex than with a normal floor guardian.": "与暗影的战斗也比普通的楼层守护者更难和更复杂。",
    "The first encounter with Shadow is not guaranteed. We believe that the more potential you have, the sooner you meet the Shadow.": "不能保证第一次遇到暗影。我们相信你的潜力越大，你就会越早遇见暗影。",
    "The large beast lays motionlessly.": "那头大野兽一动不动地躺着。",
    "Torches of magical nature line the walls, providing dim light.": "墙上排列着魔法性质的火把，提供昏暗的光线。",
    "What do you want to know?": "你想知道什么？",
    "You can have these. If you need even more then I wish you the best of luck": "你可以拿着这些。如果你需要更多，那么我祝你好运",
    "Rune - Fire Arrow": "符文 - 火焰箭",
    "Spider Silk": "蜘蛛丝",
    "Very durable and flexible, can be processed into string.": "非常耐用和灵活，可以加工成弦。",
    "Go deeper (infinite)": "前往更深处（无限）",
    "Mine Ore": "开采矿石",
    "A bat wing, might have some use in alchemy.": "蝙蝠的翅膀，也许可以用来炼金。",
    "Wolf used <Maul": "狼 使用了 <锤击",
    "Holy Slime used <Holy Bolt": "神圣系史莱姆 使用了 <神圣之箭",
    "Shadow Slime used <Shadow Bolt": "暗影系史莱姆 使用了 <暗影之箭",
    "Warthog used <Tackle": "疣猪 使用了 <抱摔",
    "Mastery over the fire element.": "精通火系元素。",
    "Tackle": "抱摔",
    "Tackle.": "抱摔。",
    "Stun": "眩晕",
    "Holy Slime": "神圣系史莱姆",
    "Shadow Slime": "暗影系史莱姆",
    "Mining Experience": "采矿经验值",
    "A boar tusk, heavy.": "一根野猪牙，很重。",
    "EXP": "经验值",
    "Drops": "掉落",
    "Forest": "森林",
    "Spells": "法术",
    "Shadow Burn": "暗影燃烧",
    "Shadow Lock": "暗影锁",
    "Impale": "刺穿",
    "Town": "小镇",
    "The enemy spell.": "敌人的法术。",
    "Chance": "几率",
    "(base).": "(基础).",
    "Basic information": "基础信息",
    "Gorglott, the Sponge": "格洛特，海绵",
    "Burn the enemy's shadow.": "燃烧敌人的影子。",
    "A goat horn, pointy.": "山羊的角，尖尖的。",
    "A quick swipe with sharp claws.": "用锋利的爪子快速滑动。",
    "Additional constraints may be applicable (e.g. casting the spell only once per battle).": "额外的限制可能是适用的（例如，每次战斗只能施放一次法术）。",
    "Dangerous attack with a pointy horn.": "用尖角进行危险的攻击。",
    "Enemies can both attack and cast spells in the same game tick.": "敌人可以在同一游戏时间内攻击和施放法术。",
    "Kacadu's Shadow, the Examiner": "卡卡杜的影子，考官",
    "Locks the enemy shadow in place, making them unable to act.": "锁定敌人的影子，使他们无法行动。",
    "Provided the enemy has enough required resource, all spells can be casted within the same tick.": "如果敌人有足够的资源，所有的法术都可以在同一时间内施放。",
    "The chance to cast a spell in each tick.": "每一刻(tick)施放一个法术的几率。",
    "The health threshold an enemy has to reach to be able to cast this spell.": "敌人必须达到相应生命值才能施放此法术。",
    "The mana threshold an enemy has to reach to be able to cast this spell.": "敌人必须达到相应法力值才能施放此法术。",
    "This creature does not cast any spells.": "该生物不施放任何法术。",
    "String": "弓弦",
    "A helpful guy providing information to rookie Travelers.": "一个乐于助人的人，为新手旅行者提供信息。",
    "A hunter I have met after beating a bear in the forest cave.": "我在森林洞穴里打败了一只熊后遇到了一个猎人。",
    "A simple iron earring.": "一个简单的铁耳环。",
    "A simple iron ring.": "一个简单的铁环。",
    "A sword made out of iron, pretty reliable.": "一把铁做的剑，相当可靠。",
    "Accept a Blessing.": "接受祝福。",
    "All Crafting Skills Experience": "所有锻造技能经验",
    "Apply status effect 10 000 times.": "应用状态效果10 000次。",
    "As an example, he mentioned bear and hunting bow preserving its pelt perfectly.": "举个例子，他提到了熊和狩猎如何完美地保存毛皮。",
    "Basic training sword, made out of wood.": "基本训练用的剑，木头做的。",
    "Big Game Hunter": "大型猎手",
    "Child of Fortune": "幸运之子",
    "Combat Mastery Experience": "战斗精通经验",
    "Connoisseur": "鉴赏家",
    "Crafter": "工匠",
    "Drink something for the very first time.": "第一次喝点东西。",
    "Eat something for the very first time.": "第一次吃东西。",
    "Grants the \"Traveler\" title": "授予“旅行者”称号",
    "He also mentioned something about being a traveler.": "他还提到了作为一个旅行者。",
    "He gave me advice that my equipment might have an effect on the materials harvested from enemies.": "他告诉我，我的装备可能会影响从敌人那里收获的材料。",
    "He is selling books that teach everything there is to know about a monster.": "他卖的书教关于怪物的一切知识。",
    "Holy Sting": "神圣的刺",
    "Hungry no more": "不再挨饿",
    "I can find him at the bar in the Adventurers' Guild.": "我可以在冒险家公会的酒吧里找到他。",
    "I can usually meet him in the Hunter's Cabin in the evening.": "我通常晚上可以在猎人小屋见他。",
    "I met a woman called Kathryn, she seems to know what's going on when it comes to the tower and these blessings...": "我遇到了一个叫凯思琳的女人，她似乎知道发生了什么，当谈到塔和这些祝福时……",
    "I should meet her in the Adventurers' Guild's Bar when I have some spare time.": "我应该在有空闲时间的时候去冒险家公会酒吧见她。",
    "I should talk to him in the Hunter's Cabin when I am free.": "等我有空了，我应该到猎人小屋去跟他谈谈。",
    "I should talk to Jake in the Bar if I want more information.": "如果我想了解更多信息，我应该和酒吧的杰克谈谈。",
    "Iron Sword": "铁剑",
    "It was probably water, right?": "可能是水，对吧？",
    "Just like acquiring a card, but without having to hunt for days.": "就像拿到一张卡，但不用找好几天。",
    "Kathryn": "凯瑟琳",
    "Left Accessory": "左侧配饰",
    "Lifewater": "生命之水",
    "Lomsi": "洛姆西",
    "Made out of spider silk. Necessary component when crafting clothes.": "用蜘蛛丝做的。制作衣服时的必要成分。",
    "Met her again, she was pretty surprised that I met the 'Shadow', as she calls it, on the very first floor. Apparently that's not normal. Wonder where and when we'll meet again.": "再次见到她时，她很惊讶我在一楼就遇到了她所说的“影子”。显然这是不正常的。不知道我们何时何地能再见面。",
    "Mild Spender": "适度消费",
    "Obtain 5 cards.": "获得5张卡片。",
    "Obtain your first card.": "拿到你的第一张卡。",
    "Powerful Curse": "强大的诅咒",
    "Shadow Sting": "暗影之刺",
    "Spend a total of 1 gold coin.": "总共花费1个金币",
    "The taste of water": "水的味道",
    "Use a health potion for the very first time.": "第一次使用生命药水。",
    "Valuable material used for many things. Perfect for crafting durable weapons and armor.": "用于许多东西的有价值的材料。非常适合制作耐用的武器和盔甲。",
    "Alchemy skill. Each point equals 1% experience increase.": "炼金术技能。每点等于增加1%的经验值。",
    "Blacksmithing skill. Each point equals 1% experience increase.": "锻造技能。每点等于增加1%的经验值。",
    "Blessing of Power": "力量祝福",
    "Chronomancy skill. Each point equals 1% experience increase.": "计时技能。每点等于增加1%的经验值。",
    "Combat Mastery (Perk)": "战斗精通（Perk）",
    "Combat Mastery skill. Each point equals 1% experience increase.": "战斗精通技能。每点等于增加1%的经验值。",
    "Cooking skill. Each point equals 1% experience increase.": "烹饪技能。每点等于增加1%的经验值。",
    "Earth Affinity skill. Each point equals 1% experience increase.": "大地亲和技能。每点等于增加1%的经验值。",
    "Enchanting skill. Each point equals 1% experience increase.": "迷人的技能。每点等于增加1%的经验值。",
    "enemies of the Beast": "野兽敌人",
    "enemies of the Construct": "结构敌人",
    "enemies of the Formless": "无形敌人",
    "enemies of the Humanoid": "人形敌人",
    "enemies of the Insect": "昆虫敌人",
    "enemies of the Plant": "植物敌人",
    "Fire Affinity skill. Each point equals 1% experience increase.": "火焰亲和技能。每点等于增加1%的经验值。",
    "Gluttony skill. Each point equals 1% experience increase.": "暴食技能。每点等于增加1%的经验值。",
    "Herbalism skill. Each point equals 1% experience increase.": "草药学技能。每点等于增加1%的经验值。",
    "Holy Affinity skill. Each point equals 1% experience increase.": "神圣亲和技能。每点等于增加1%的经验值。",
    "It's magic!": "这是魔法!",
    "Jewelcrafting skill. Each point equals 1% experience increase.": "珠宝加工技能。每点等于增加1%的经验值。",
    "Leatherworking skill. Each point equals 1% experience increase.": "皮革加工技能。每点等于增加1%的经验值。",
    "Mana Control skill. Each point equals 1% experience increase.": "法力控制技能。每点等于增加1%的经验值。",
    "Mana!": "法力!",
    "Mining (Perk)": "采矿（福利）",
    "Mining skill. Each point equals 1% experience increase.": "采矿技能。每点等于增加1%的经验值。",
    "Mutilation skill. Each point equals 1% experience increase.": "切割能力。每点等于增加1%的经验值。",
    "Runecarving skill. Each point equals 1% experience increase.": "符文雕刻技能。每点等于增加1%的经验值。",
    "Scrollcrafting skill. Each point equals 1% experience increase.": "卷轴制作技能。每点等于增加1%的经验值。",
    "Shadow Affinity skill. Each point equals 1% experience increase.": "暗影亲和技能。每点等于增加1%的经验值。",
    "Studying skill. Each point equals 1% experience increase.": "学习技能。每点等于增加1%的经验值。",
    "Tailoring skill. Each point equals 1% experience increase.": "裁剪技巧。每点等于增加1%的经验值。",
    "Tenacity (Perk)": "坚韧（福利）",
    "Tenacity skill. Each point equals 1% experience increase.": "坚韧技能。每点等于增加1%的经验值。",
    "Trading skill. Each point equals 1% experience increase.": "交易技能。每点等于增加1%的经验值。",
    "Water Affinity skill. Each point equals 1% experience increase.": "水系亲和技能。每点等于增加1%的经验值。",
    "Wind Affinity skill. Each point equals 1% experience increase.": "风系亲和技能。每点等于增加1%的经验值。",
    "Woodcutting skill. Each point equals 1% experience increase.": "伐木的技能。每点等于增加1%的经验值。",
    "Woodworking skill. Each point equals 1% experience increase.": "木工技能。每点等于增加1%的经验值。",
    "Bandage.": "绷带。",
    "Basic wooden staff with some pieces of crystal embedded in the wood.": "基本的木制手杖，一些水晶镶嵌在木头里。",
    "Blacksmithing manual": "锻造手册",
    "Blacksmithing Theory": "锻造理论",
    "Cloth": "布料",
    "Cloth.": "布料。",
    "Come back in about three days, I should have the cloak ready for you by then.": "三天后再来吧，到那时我会把斗篷准备好给你的。",
    "Come back later": "待会再来",
    "Crafted at the Blacksmithing station.": "在铁匠站制作。",
    "Crafted at the Tailoring station.": "在裁剪站精心制作。",
    "Deliver the ore": "提供矿石",
    "Devon's Anvil's Assortment": "德文铁砧的分类",
    "Doubles the chance of finding a herb amongst weeds.": "在杂草中找到草本植物的机会增加一倍。",
    "Have him make it for you": "让他帮你做",
    "His gaze pressures you to buy something...": "他的目光迫使你去买东西……",
    "However, I would greatly appreciate if you could get a pelt for me as well. I really like it.": "不过，如果你也能给我买一件毛皮，我将不胜感激。我真的很喜欢。",
    "I could also just give you the diagram for you to make it yourself. I am quite curious about the result, so it will be free of charge.": "我也可以给你们一个图表让你们自己做。我对结果很好奇，所以免费。",
    "It should make a very nice cloak. If you bring me two pieces, I will make the cloak for you. One of the pelts for the cloak itself, and the other one as a payment.": "这应该是一件很漂亮的斗篷。你若拿两块来，我就给你做这件外衣。一块皮用来做斗篷，另一块作为报酬。",
    "Just read it and you will know how to make one yourself.": "只要读读它，你就会知道如何自己做一个。",
    "Leathers": "皮革",
    "Make it yourself": "自己制作",
    "Much quieter than during the day.": "比白天安静多了。",
    "Nice job, kid! You actually did it": "干得好，孩子！你真的做到了",
    "Novice Hat": "新手帽子",
    "Novice Hat.": "新手帽子。",
    "Novice Robe": "新手长袍",
    "Novice Robe.": "新手长袍。",
    "Novice Shoes": "新手鞋子",
    "Novice Shoes.": "新手鞋子。",
    "Novice Staff": "新手法杖",
    "Novice Staff.": "新手法杖。",
    "Oh, that's quite the piece you've got there": "哦，你拿的那块还不错",
    "Pickaxe.": "鹤嘴锄。",
    "Processed material, mostly used in making warm clothes. Also the material of choice for crafting magical robes.": "加工过的材料，主要用于制作保暖衣服。也是制作魔法长袍的首选材料。",
    "Show him the Pristine Bear Pelt": "给他看看原始熊皮",
    "Sickle": "镰刀",
    "Sickle used for gathering herbs.": "用来采集草药的镰刀。",
    "Smooth to the touch, imbued with mana.": "摸起来很光滑，充满魔力。",
    "Smooth to the touch, imbued with mana. Provides no physical protection but enhances magical capabilities.": "摸起来很光滑，充满魔力。不能提供物理保护，但可以增强魔法能力。",
    "Tailoring manual": "裁剪手册",
    "Tailoring Theory": "裁剪理论",
    "Thanks for the pelt": "谢谢你的毛皮",
    "Thanks, that ore should last me a while, here is a diagram for the Pickaxe.": "谢谢，这个矿应该够我用一阵子了，这是鹤嘴锄的示意图。",
    "Woodworking manual": "木工手册",
    "Woodworking Theory": "木工理论",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Weed": "杂草",
    "Chicken": "鸡",
    "Rabbit": "兔子",
    "Slayer": "杀手",
    "Poison Bite": "毒咬",
    "Ouch": "哎哟",
    "First Blood": "第一滴血",
    "A": "攻击",
    "W": "武器",
    "R": "种族",
    "BUR": "燃烧抵抗",
    "BLR": "流血抵抗",
    "PR": "中毒抵抗",
    "HP": "生命值",
    "MP": "法力值",
    "HPT": "生命值阈值",
    "Health Threshold": "生命值阈值",
    "MPT": "法力值阈值",
    "Mana Threshold": "法力值阈值",
    "DEF": "防御",
    "DEX": "灵巧",
    "STR": "力量",
    "INT": "智力",
    "QTY": "数量",
    "DR": "伤害减免",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "ABC": "ABC",
    "Monday": "周一",
    "Tuesday": "周二",
    "Wednesday": "周三",
    "Thursday": "周四",
    "Friday": "周五",
    "Saturday": "周六",
    "Sunday": "周日",
    "": "",
    ", ": ", ",
    "(": "(",
    "+": "+",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': '护甲',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': '武器',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需造成的的前缀，此处可以截取语句开头部分的内容进行汉化
//例如: Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头: "Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑: ",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式: ",
    "In-line Exponent: ": "直列指数: ",
    "Single-Tab Mode: ": "单标签模式: ",
    "Time Played: ": "已玩时长: ",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示: ",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Player": "玩家",
    "Teaches how to make ": "教授如何制作 ",
    "Critical chance: ": "暴击率: ",
    "Value: ": "值: ",
    " Prof.": "教授",
    "Increases the damage you deal against enemies of the ": "增加你对 ",
    "Increases the damage you deal against enemies with ": "增加你对 ",
    "Increases the damage you deal with ": "增加你对 ",
    "Unlocked: ": "已解锁: ",
    "Duration: ": "持续时间: ",
    "Basement: ": "地下室: ",
    " hit Rat for ": " 对 老鼠 造成伤害 ",
    " hit Bat for ": " 对 蝙蝠 造成伤害 ",
    " hit Bear for ": " 对 熊 造成伤害 ",
    " hit Warthog for ": " 对 疣猪 造成伤害 ",
    " hit Wolf for ": " 对 狼 造成伤害 ",
    " hit Iron Vein for ": " 对 铁矿脉 造成伤害 ",
    " hit Spider for ": " 对 蜘蛛 造成伤害 ",
    " hit Rabbit for ": " 对 兔子 造成伤害 ",
    " hit Slime for ": " 对 史莱姆 造成伤害 ",
    " hit Shadow Slime for ": " 对 暗影系史莱姆 造成伤害 ",
    " hit Holy Slime for ": " 对 神圣系史莱姆 造成伤害 ",
    " hit Holy Slimer for ": " 对 神圣系史莱姆 造成伤害 ",
    " hit Shadow Slimer for ": " 对 暗影系史莱姆 造成伤害 ",
    " hit Mountain Goat for ": " 对 山羊 造成伤害 ",
    " hit Water Slime for ": " 对 水系史莱姆 造成伤害 ",
    " hit Fire Slime for ": " 对 火系史莱姆 造成伤害 ",
    " hit Chicken for ": " 对 鸡 造成伤害 ",
    " hit Weed for ": " 对 杂草 造成伤害 ",
    " hit Tree for ": " 对 树 造成伤害 ",
    " hit Training Dummy for ": " 对 训练假人 造成伤害 ",
    "EXP + ": "经验值 + ",
    "New achievement unlocked! ": "新成就解锁了! ",
    "Spider hit Player for ": "蜘蛛 击中了 玩家 并造成伤害 ",
    "Bear hit Player for ": "熊 击中了 玩家 并造成伤害 ",
    "Bat hit Player for ": "蝙蝠 击中了 玩家 并造成伤害 ",
    "Chicken hit Player for ": "鸡 击中了 玩家 并造成伤害 ",
    "Holy Slimer hit Player for ": "神圣系史莱姆 击中了 玩家 并造成伤害 ",
    "Shadow Slimer hit Player for ": "暗影系史莱姆 击中了 玩家 并造成伤害 ",
    "Earth Slime hit Player for ": "土系史莱姆 击中了 玩家 并造成伤害 ",
    "Water Slime hit Player for ": "水系史莱姆 击中了 玩家 并造成伤害 ",
    "Fire Slime hit Player for ": "火系史莱姆 击中了 玩家 并造成伤害 ",
    "Wind Slime hit Player for ": "风系史莱姆 击中了 玩家 并造成伤害 ",
    "Holy Slime hit Player for ": "神圣系史莱姆 击中了 玩家 并造成伤害 ",
    "Shadow Slime hit Player for ": "暗影系史莱姆 击中了 玩家 并造成伤害 ",
    "Mountain Goat hit Player for ": "山羊 击中了 玩家 并造成伤害 ",
    "Warthog hit Player for ": "疣猪 击中了 玩家 并造成伤害 ",
    "Wolf hit Player for ": "狼 击中了 玩家 并造成伤害 ",
    "Rat hit Player for ": "老鼠 击中了 玩家 并造成伤害 ",
    "Rabbit hit Player for ": "兔子 击中了 玩家 并造成伤害 ",
    "Rat used ": "老鼠使用了 ",
    "<": "<",
    "Training Grounds: ": "训练场: ",
    "Training Dummy hit Player for ": "训练假人 击中 玩家 并造成伤害 ",
    "Next contracts at: ": "下一次合同时间: ",
    "Reputation: ": "声誉: ",
    "Forest Outskirts: ": "森林外围: ",
    "Increase exp gained for the ": "增加 ",
    "Reduces the damage you receive from ": "降低你受到的 ",
    "Reduces the damage you receive from enemies of the ": "降低你受到的 ",
    "Consumable / ": "消耗品 / ",
    "Readable / ": "可阅读 / ",
    "Equip / ": "装备 / ",
    "Beast Hatred ": "野兽仇恨 ",
    "Inside Tower - ": "塔内 - ",
    "Diagram - ": "图表 - ",
    "Reading amount left: ": "剩余阅读量",
    "Cost: ": "成本: ",
    "Fire Arrow> dealt ": "火焰箭> 造成了 ",
    "Fire Arrow> dealt ": "火焰箭> 造成 ",
    "Water Splash> dealt ": "水花飞溅> 造成了 ",
    "Rune - ": "符文 - ",
    "Enchant - ": "附魔 - ",
    "Enchant ": "附魔 ",
    "Card - ": "卡片 - ",
    "Scroll - ": "卷轴 - ",
    "Buy access to ": "购买 ",
    "Leave ": "离开",
    "A weak enchant that increases the user's ": "一个微弱的附魔，增加一点点使用者的 ",
    ", you will gain 100% more ": "，你将获得 100% 的 ",
    "Forest Depths: ": "森林深处",
    "Learned how to make ": "学会了如何制作 ",
    "Formless Hatred + ": "无形仇恨 + ",
    "[F] ": "[F] ",
    "[E] ": "[E] ",
    "[D] ": "[D] ",
    "[C] ": "[C] ",
    "[B] ": "[B] ",
    "[A] ": "[A] ",
    "[S] ": "[S] ",
    "Construct Hatred + ": "结构仇恨 + ",
    "Insect Hatred + ": "昆虫仇恨 + ",
    "Plant Hatred + ": "植物仇恨 + ",
    "Impale> dealt ": "刺穿> 造成 ",
    "Stone Bullet> dealt ": "石弹> 造成 ",
    "Holy Bolt> dealt ": "神圣之箭> 造成 ",
    "Shadow Bolt> dealt ": "暗影之箭> 造成 ",
    "Please bring me ": "请给我一些 ",
    "Bestiary entry unlocked: ": "怪物图鉴已解锁: ",
    "Chance: ": "几率: ",
    "Abandoned Mine: ": "废弃矿井: ",
    "Cave: ": "洞穴: ",
    "Defeating this enemy will grant ": "击败该敌人将获得 ",
    "Tower ": "塔 ",
    "Total skill level ups equal to ": "累计技能等级达到 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需造成的的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如: 13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾: " Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ">": ">",
    "!": "!",
    ":": ":",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    ' I:': ' I:',
    ' II:': ' II:',
    ' III:': ' III:',
    ' IV:': ' IV:',
    ' V:': ' V:',
    ' VI:': ' VI:',
    ' VII:': ' VII:',
    ' VIII:': ' VIII:',
    ' X:': ' X:',
    ' XI:': ' XI:',
    ' XII:': ' XII:',
    ' XIII:': ' XIII:',
    ' XIV:': ' XIV:',
    ' XV:': ' XV:',
    ' XVI:': ' XVI:',
    " race. Each point equals 1% damage increase.": " 种族敌人造成的伤害。每增加1点相当于增加1%的伤害。",
    " element. Each point equals 1% damage increase.": " 元素敌人造成的伤害。每增加1点相当于增加1%的伤害。",
    " attacks. Each point equals 1% damage increase.": " 攻击敌人造成的伤害。每增加1点相当于增加1%的伤害。",
    " has been slain": " 已被击杀",
    ",": ",",
    " skill.  Each point equals 1% experience increase.": " 技能的经验值。每点等于增加1%的经验值。",
    " attacks.  Each point equals 1% reduction (up to 100%).": " 系攻击的伤害。每点等于减少1%（最多100%）。",
    " attacks. Each point equals 1% reduction (up to 100%).": " 系攻击的伤害。每点等于减少1%（最多100%）。",
    " race. Each point equals 1% reduction (up to 100%).": " 种族的伤害。每点等于减少1%（最多100%）。",
    " Station": "站点 的访问权限",
    " a little.": "。",
    " experience for 300 seconds.": " 经验值持续 300 秒。",
    " fragments, scrolls as an extra reward": " 碎片，卷轴作为额外的奖励",
    " second)": " 秒)",
    " or higher.": " 级或以上。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+ ([\d\.]+)\%$/,
    /^([\d\.]+)\%.$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)t$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\+ ([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)\/([\d\.,]+) ([\d\.,]+):([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+). ([\d\.,]+). ([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字: (\d+)
//字母加数字: ([\d\.]+[A-Za-z])
//逗号: ([\d\.,]+)
//小数点: ([\d\.]+)
//原样输出的字段: (.+)
//换行加空格: \n(.+)
//&nbsp;空格: \xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Kill (.+) enemies with earth armor.$/, '使用 土 系护甲击杀 $1 名敌人。'],
    [/^Kill (.+) enemies with neutral armor.$/, '使用 中立 系护甲击杀 $1 名敌人。'],
    [/^Kill (.+) enemies with holy armor.$/, '使用 神圣 系护甲击杀 $1 名敌人。'],
    [/^Kill (.+) enemies with shadow armor.$/, '使用 暗影 系护甲击杀 $1 名敌人。'],
    [/^Kill (.+) enemies with fire armor.$/, '使用 火 系护甲击杀 $1 名敌人。'],
    [/^Kill (.+) enemies with water armor.$/, '使用 水 系护甲击杀 $1 名敌人。'],
    [/^Kill (.+) enemies with wind armor.$/, '使用 风 系护甲击杀 $1 名敌人。'],
    [/^Take (.+) magical damage.$/, '受到 $1 魔法伤害。'],
    [/^Take (.+) physical damage.$/, '受到 $1 物理伤害。'],
    [/^Take (.+) earth damage.$/, '受到 $1 土系伤害。'],
    [/^Take (.+) fire damage.$/, '受到 $1 火系伤害。'],
    [/^Take (.+) water damage.$/, '受到 $1 水系伤害。'],
    [/^Take (.+) wind damage.$/, '受到 $1 风系伤害。'],
    [/^Take (.+) shadow damage.$/, '受到 $1 暗影系伤害。'],
    [/^Take (.+) holy damage.$/, '受到 $1 神圣系伤害。'],
    [/^Kill (.+) construct enemies.$/, '击杀 $1 结构敌人。'],
    [/^Kill (.+) beast enemies.$/, '击杀 $1 野兽敌人。'],
    [/^Kill (.+) plant enemies.$/, '击杀 $1 植物敌人。'],
    [/^Kill (.+) enemies.$/, '击杀 $1 敌人。'],
    [/^Deal (.+) fire damage.$/, '造成 $1 火系 伤害。'],
    [/^Deal (.+) earth damage.$/, '造成 $1 土系 伤害。'],
    [/^Deal (.+) water damage.$/, '造成 $1 水系 伤害。'],
    [/^Deal (.+) wind damage.$/, '造成 $1 风系 伤害。'],
    [/^Slay (.+) bosses.$/, '击杀 $1 Boss。'],
    [/^Read (.+) books.$/, '阅读 $1 本书。'],
    [/^Finish (.+) quests.$/, '完成 $1 任务。'],
    [/^Craft (.+) items.$/, '制作 $1 物品。'],
    [/^Cast (.+) spells.$/, '施放 $1 法术。'],
    [/^Eat something (.+) times.$/, '吃东西 $1 次。'],
    [/^Use (.+) mana.$/, '使用 $1 法力。'],
    [/^Reach level (.+) in Combat Mastery.$/, '战斗精通 达到 $1 级。'],
    [/^Reach level (.+) in Woodcutting.$/, '伐木 达到 $1 级。'],
    [/^Reach level (.+) in Mining.$/, '采矿 达到 $1 级。'],
    [/^Deals (.+) of$/, '造成 $1 的'],
    [/^Obtain (.+) items.$/, '获得 $1 物品。'],
    [/^Floor (.+) \- Guardian: (.+)$/, '层数 $1 - 守护者: $2'],
    [/^Floor (.+), Guardian Room$/, '层数 $1, 守护室'],
    [/^Fire Arrow\> dealt (.+) damage$/, '火焰箭\> 造成了 $1 伤害'],
    [/^ used \<(.+) Fire Arrow$/, ' 使用了 \<$1 火焰箭'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\- ([\d\.]+) Reputation$/, '\- $1 声誉'],
    [/^\+ ([\d\.]+) reputation.$/, '\+ $1 声誉。'],
    [/^\+ ([\d\.]+) Reputation$/, '\+ $1 声誉'],
    [/^\+ ([\d\.]+) per level$/, '\+ $1 每级'],
    [/^([\d\.]+)\% per level$/, '1\% 每级'],
    [/^\+ ([\d\.]+)\% per level$/, '\+ $1\% 每级'],
    [/^\+([\d\.]+) Reputation$/, '\+$1 声誉'],
    [/^([\d\.]+) mana \+ ([\d\.]+)\% maximum mana$/, '$1 法力 + $2\% 法力值上限'],
    [/^([\d\.]+) health \+ ([\d\.]+)\% maximum health$/, '$1 生命值 + $2\% 生命值上限'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Days$/, '$1 天'],
    [/^([\d\.,]+) damage$/, '$1 伤害'],
    [/^STR \+ ([\d\.,]+), INT \+ ([\d\.,]+), Max HP \+ ([\d\.,]+), Max MP \+ ([\d\.,]+)$/, '力量 + $1, 智力 + $2, 生命值上限 + $3, 法力值上限 + $4'],
    [/^\(([\d\.,]+) seconds\)$/, '($1 秒)'],
    [/^Level: ([\d\.,]+) \| Exp: (.+)$/, '等级: $1 \| 经验值: $2'],
    [/^Enter Floor ([\d\.,]+)$/, '进入层数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Level ([\d\.,]+):$/, '等级 $1:'],
    [/^Floor ([\d\.,]+)$/, '层数 $1'],
    [/^Floor ([\d\.,]+): ([\d\.,]+) \/ ([\d\.,]+)$/, '层数 $1: $2 / $3'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Mana Control has reached level ([\d\.,]+)$/, '法力控制 达到了 $1 级'],
    [/^Trading has reached level ([\d\.,]+)$/, '交易 达到了 $1 级'],
    [/^Studying has reached level ([\d\.,]+)$/, '学习 达到了 $1 级'],
    [/^Mutilation has reached level ([\d\.,]+)$/, '切割 达到了 $1 级'],
    [/^Herbalism has reached level ([\d\.,]+)$/, '草药学 达到了 $1 级'],
    [/^Fire Affinity has reached level ([\d\.,]+)$/, '火系亲和力 达到了 $1 级'],
    [/^Combat Mastery has reached level ([\d\.,]+)$/, '战斗精通 达到了 $1 级'],
    [/^Mining has reached level ([\d\.,]+)$/, '采矿 达到了 $1 级'],
    [/^Woodcutting has reached level ([\d\.,]+)$/, '伐木 达到了 $1 级'],
    [/^Tenacity has reached level ([\d\.,]+)$/, '坚韧 达到了 $1 级'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) reputation required.$/, '$1 声誉要求。'],
    [/^Cost: (.+) points$/, '成本: $1 点数'],
    [/^Req: (.+) elves$/, '要求: $1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求: $1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途: $1\/'],
    [/^workers: (\d+)\/$/, '工人: $1\/'],

]);